//! Renders the frozen, per-version shot log schema that variegated-plantlet-ts reads.
//!
//! Unlike `frontend/src/schemas/schemas.ts`, nothing regenerates this on a build. It runs
//! by hand, once per [`variegated_controller_types::SHOT_LOG_FORMAT_VERSION`], and its
//! output is committed to the plantlet repository where it must never change again.
//!
//! That rule is the whole design. A shot written to a card today is decoded by whatever
//! reads it years from now, and postcard is positional and non-self-describing: a schema
//! that followed the Rust types forward would not fail on an older file, it would
//! silently mis-decode every one of them. So each version gets a file, and each file is
//! correct for exactly the revision that produced it.

use std::io;
use std::path::Path;

use crc::{Crc, CRC_32_ISCSI};

use crate::{emit, fixtures, roots};

/// Write `schemas/v<N>.ts` and `fixtures/generated/v<N>.{bin,json}` under `out_dir`.
///
/// Refuses to overwrite an existing schema unless `force`. Regenerating a released
/// version is the one operation this must not make easy: the file *is* the format, and
/// rewriting it would turn a deliberate version bump into an accident nobody reviews.
pub fn write(out_dir: &Path, version: u32, force: bool) -> io::Result<()> {
    let schemas_dir = out_dir.join("schemas");
    let schema_path = schemas_dir.join(format!("v{version}.ts"));

    if schema_path.exists() && !force {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!(
                "{} already exists.\n\
                 A released schema is frozen: bump SHOT_LOG_FORMAT_VERSION and export the \
                 new version beside it, rather than regenerating this one. Pass --force \
                 only if version {version} has never shipped.",
                schema_path.display()
            ),
        ));
    }

    std::fs::create_dir_all(&schemas_dir)?;
    std::fs::write(&schema_path, render(version))?;

    let fixture_dir = out_dir.join("fixtures").join("generated");
    std::fs::create_dir_all(&fixture_dir)?;

    let shot = fixtures::canonical_shot();
    // Both encodings, for the reason the fixtures module gives: the bytes catch wrong
    // node kinds, nesting, field counts and variant order, and are blind to field names
    // and to two same-typed fields being swapped. Only the JSON catches those.
    //
    // `to_allocvec_crc32`, not `to_allocvec`. A stored shot is exactly what
    // `shot_log_storage.rs` writes -- the postcard encoding followed by a CRC-32/ISCSI
    // trailer, no header and no container -- and that is what a downloaded `.BIN`
    // contains and what plantlet is handed. A fixture without the trailer would be in a
    // format no machine emits, and the decoder it exists to test would refuse it.
    let crc = Crc::<u32>::new(&CRC_32_ISCSI);
    let bytes =
        postcard::to_allocvec_crc32(&shot, crc.digest()).expect("the canonical shot must serialize");
    std::fs::write(fixture_dir.join(format!("v{version}.bin")), &bytes)?;

    // The same bytes again, as a module.
    //
    // `.bin` is the canonical artifact and the one a non-JavaScript consumer wants, but
    // it cannot be read everywhere it is needed: the Worker's tests run inside workerd,
    // which has no filesystem, and a cross-package data module resolves outside the
    // worker's module root and fails to load. A module has none of those problems and
    // works unchanged in Node, in workerd and in a browser.
    std::fs::write(
        fixture_dir.join(format!("v{version}.ts")),
        render_bytes_module(version, &bytes),
    )?;
    std::fs::write(
        fixture_dir.join(format!("v{version}.json")),
        serde_json::to_string_pretty(&shot).expect("the canonical shot must serialize as JSON"),
    )?;

    Ok(())
}

/// The fixture bytes as a TypeScript module, base64 so the source stays readable.
fn render_bytes_module(version: u32, bytes: &[u8]) -> String {
    format!(
        "// @generated by variegated-schema-export --shot-log -- DO NOT EDIT.\n\
         //\n\
         // The canonical shot log format version {version} fixture, byte for byte what\n\
         // `postcard::to_allocvec_crc32` produced from the Rust value. Identical to\n\
         // v{version}.bin, in a form that can be imported anywhere: workerd has no\n\
         // filesystem, so a test running inside it cannot read the `.bin`.\n\
         //\n\
         // `atob` is available in Node 18+, in workerd and in every browser.\n\
         \n\
         export const SHOT_LOG_V{version}_FIXTURE: Uint8Array = Uint8Array.from(\n  \
         atob(\n    '{}'\n  ),\n  (c) => c.charCodeAt(0)\n);\n",
        base64(bytes)
    )
}

/// Minimal standard base64. Avoids a dependency for one call.
fn base64(bytes: &[u8]) -> String {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::new();
    for chunk in bytes.chunks(3) {
        let b = [chunk[0], *chunk.get(1).unwrap_or(&0), *chunk.get(2).unwrap_or(&0)];
        let n = ((b[0] as u32) << 16) | ((b[1] as u32) << 8) | b[2] as u32;
        out.push(ALPHABET[(n >> 18) as usize & 63] as char);
        out.push(ALPHABET[(n >> 12) as usize & 63] as char);
        out.push(if chunk.len() > 1 { ALPHABET[(n >> 6) as usize & 63] as char } else { '=' });
        out.push(if chunk.len() > 2 { ALPHABET[n as usize & 63] as char } else { '=' });
    }
    out
}

/// The full contents of `v<N>.ts`.
fn render(version: u32) -> String {
    let generated = emit::generate(roots::shot_log_registry(), "");
    format!("{}\n{}", header(version), body_of(&generated))
}

fn header(version: u32) -> String {
    format!(
        "// @generated by variegated-schema-export --shot-log -- DO NOT EDIT.\n\
         //\n\
         // The postcard schema for shot log format version {version}, generated from\n\
         // variegated-controller-types at the revision that defined that version.\n\
         //\n\
         // FROZEN. Field order and enum variant order are the file format: postcard is\n\
         // positional and non-self-describing, so a field out of order silently\n\
         // mis-decodes everything after it. This file is correct for version {version}\n\
         // and for nothing else, and it must never be regenerated against newer Rust\n\
         // types. A format change means a new SHOT_LOG_FORMAT_VERSION and a new file\n\
         // beside this one -- the old shots do not stop existing.\n\
         //\n\
         // Regenerating: check out the variegated-controller-types revision that defines\n\
         // the version, then run\n\
         //   variegated-schema-export --shot-log <plantlet>/packages/shot-log\n"
    )
}

/// Drop the shared emitter's header, keeping everything from the import block on.
///
/// [`emit::generate`] opens with the header describing the live frontend file. Every line
/// of it is wrong here, and one is actively harmful: it tells the reader how to
/// regenerate, which is the one thing this file must not invite.
fn body_of(generated: &str) -> String {
    match generated.split_once("\nimport {") {
        Some((_, rest)) => format!("import {{{rest}"),
        // The emitter always writes an import block, since every schema uses at least one
        // combinator. Falling back whole is still better than emitting nothing.
        None => generated.to_string(),
    }
}
