//! Renders the frozen, per-version uplink schema that variegated-plantlet-ts reads.
//!
//! The sibling of [`crate::shot_log_export`], and frozen for the same reason: postcard is
//! positional and non-self-describing, so a schema that followed the Rust types forward would
//! not fail against an older machine, it would silently mis-decode every message from one.
//!
//! The difference is what "older" means. A shot log outlives the firmware that wrote it, so
//! every version's schema has to survive forever. An uplink session does not — both ends are
//! present, and a mismatch surfaces immediately. The freeze is still worth having, because a
//! fleet is not reflashed atomically and a machine on last month's firmware is exactly the
//! case where a silently-wrong decode does damage.

use std::io;
use std::path::Path;

use crate::{emit, fixtures, roots};

/// Write `schemas/v<N>.ts` and `fixtures/generated/uplink-v<N>.*` under `out_dir`.
///
/// Refuses to overwrite an existing schema unless `force`, for the reason the shot log's
/// export gives: the file *is* the contract, and rewriting it turns a deliberate version bump
/// into an accident nobody reviews.
pub fn write(out_dir: &Path, version: u32, force: bool) -> io::Result<()> {
    let schemas_dir = out_dir.join("schemas");
    let schema_path = schemas_dir.join(format!("v{version}.ts"));

    if schema_path.exists() && !force {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!(
                "{} already exists.\n\
                 A released schema is frozen: bump UPLINK_SCHEMA_VERSION and export the new \
                 version beside it, rather than regenerating this one. Pass --force only if \
                 version {version} has never been deployed to a machine.",
                schema_path.display()
            ),
        ));
    }

    std::fs::create_dir_all(&schemas_dir)?;
    std::fs::write(&schema_path, render(version))?;

    let fixture_dir = out_dir.join("fixtures").join("generated");
    std::fs::create_dir_all(&fixture_dir)?;

    // No CRC trailer here, unlike the shot log's fixture. A stored shot carries one because
    // nothing else protects it on a card; an uplink record is sealed by Noise, whose per-frame
    // authentication tag makes a CRC redundant. A fixture with a trailer would be in a format
    // the transport never produces.
    let messages = fixtures::canonical_uplink_messages();
    let mut modules = String::new();

    for (name, message) in &messages {
        let bytes = postcard::to_allocvec(message)
            .expect("a canonical uplink message must serialize");

        std::fs::write(fixture_dir.join(format!("uplink-v{version}-{name}.bin")), &bytes)?;
        std::fs::write(
            fixture_dir.join(format!("uplink-v{version}-{name}.json")),
            serde_json::to_string_pretty(message)
                .expect("a canonical uplink message must serialize as JSON"),
        )?;

        modules.push_str(&render_constant(name, &bytes));
    }

    // One module for all of them, rather than one per fixture. The Worker's tests run inside
    // workerd, which has no filesystem, so they cannot read the `.bin` files; a module they
    // can import works unchanged in Node, in workerd and in a browser.
    std::fs::write(
        fixture_dir.join(format!("uplink-v{version}.ts")),
        format!("{}{}", fixtures_header(version), modules),
    )?;

    Ok(())
}

fn fixtures_header(version: u32) -> String {
    format!(
        "// @generated by variegated-schema-export --uplink -- DO NOT EDIT.\n\
         //\n\
         // Canonical uplink protocol version {version} messages, byte for byte what\n\
         // `postcard::to_allocvec` produced from the Rust values. Identical to the\n\
         // matching `.bin` files, in a form that can be imported anywhere: workerd has\n\
         // no filesystem, so a test running inside it cannot read those.\n\
         //\n\
         // These are the *plaintext* of a record. On the wire each is sealed by Noise\n\
         // and preceded by an eight-byte counter; nothing here covers that framing.\n\
         //\n\
         // `atob` is available in Node 18+, in workerd and in every browser.\n\n"
    )
}

/// One fixture as an exported constant. `reply-write-refused` becomes
/// `UPLINK_V1_REPLY_WRITE_REFUSED`.
fn render_constant(name: &str, bytes: &[u8]) -> String {
    let ident = name.to_uppercase().replace('-', "_");
    format!(
        "export const UPLINK_{ident}: Uint8Array = Uint8Array.from(\n  \
         atob(\n    '{}'\n  ),\n  (c) => c.charCodeAt(0)\n);\n\n",
        base64(bytes)
    )
}

/// Minimal standard base64. Duplicated from `shot_log_export` rather than shared: the two
/// exports are frozen artifacts with different lifetimes, and a change to one must not be
/// able to alter bytes already committed for the other.
fn base64(bytes: &[u8]) -> String {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::new();
    for chunk in bytes.chunks(3) {
        let b = [chunk[0], *chunk.get(1).unwrap_or(&0), *chunk.get(2).unwrap_or(&0)];
        let n = ((b[0] as u32) << 16) | ((b[1] as u32) << 8) | b[2] as u32;
        out.push(ALPHABET[(n >> 18) as usize & 63] as char);
        out.push(ALPHABET[(n >> 12) as usize & 63] as char);
        out.push(if chunk.len() > 1 { ALPHABET[(n >> 6) as usize & 63] as char } else { '=' });
        out.push(if chunk.len() > 2 { ALPHABET[n as usize & 63] as char } else { '=' });
    }
    out
}

/// The full contents of `v<N>.ts`.
fn render(version: u32) -> String {
    let generated = emit::generate(roots::uplink_registry(), "");
    format!("{}\n{}", header(version), body_of(&generated))
}

fn header(version: u32) -> String {
    format!(
        "// @generated by variegated-schema-export --uplink -- DO NOT EDIT.\n\
         //\n\
         // The postcard schema for uplink protocol version {version}, generated from\n\
         // variegated-comms-api-types at the revision that defined that version.\n\
         //\n\
         // FROZEN. Field order and enum variant order are the wire format: postcard is\n\
         // positional and non-self-describing, and this transport carries no version\n\
         // byte, so a variant out of order does not fail -- it decodes as a different\n\
         // message. A protocol change means a new UPLINK_SCHEMA_VERSION and a new file\n\
         // beside this one, because a fleet is not reflashed all at once.\n\
         //\n\
         // What is deliberately absent: WsMessage and MachineCommand. Those belong to\n\
         // the machine's LAN socket, and the uplink envelope exists precisely so that\n\
         // authority over what the machine physically does cannot reach a remote\n\
         // server. If either appears in this file, the Rust enum has grown a reference\n\
         // it should not have.\n\
         //\n\
         // Regenerating: check out the variegated-comms-api-types revision that defines\n\
         // the version, then run\n\
         //   variegated-schema-export --uplink <plantlet>/packages/uplink\n"
    )
}

/// Drop the shared emitter's header, keeping everything from the import block on.
///
/// See [`crate::shot_log_export`]'s twin for why: the emitter's header describes the live
/// frontend file, and one of its lines tells the reader how to regenerate — the one thing a
/// frozen file must not invite.
fn body_of(generated: &str) -> String {
    match generated.split_once("\nimport {") {
        Some((_, rest)) => format!("import {{{rest}"),
        None => generated.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The uplink schema does not reach `MachineCommand`, and never may.
    ///
    /// The separate envelope exists so that authority over what the machine physically does
    /// cannot travel to a remote server. That is a claim about the *type graph*, and this is
    /// what checks it: if someone adds a variant to `UplinkMessage` or `UplinkQuery` carrying
    /// a command — or adds a field to a type already reachable from one — the schema grows a
    /// `MachineCommandSchema` and this fails.
    ///
    /// Asserted against the emitted schema rather than by reading the enum, because the
    /// hazard is reachability through several hops, which no amount of reading the envelope
    /// would reveal.
    #[test]
    fn the_uplink_schema_cannot_reach_a_machine_command() {
        let generated = body_of(&emit::generate(roots::uplink_registry(), ""));

        for forbidden in ["MachineCommandSchema", "WsMessageSchema"] {
            assert!(
                !generated.contains(forbidden),
                "{forbidden} is reachable from UplinkMessage -- the uplink envelope has \
                 grown a reference to the LAN socket's authority"
            );
        }
    }

    /// The envelope's own variants are all present, so the check above is not passing
    /// because the emitter produced nothing.
    ///
    /// A negative assertion on generated output is worth exactly as much as the evidence
    /// that the output exists; without this, deleting the registry would make the test above
    /// pass.
    #[test]
    fn the_uplink_schema_describes_the_envelope() {
        let generated = body_of(&emit::generate(roots::uplink_registry(), ""));

        for expected in [
            "UplinkMessageSchema",
            "UplinkQuerySchema",
            "QueryOutcomeSchema",
            "StatusSchema",
        ] {
            assert!(
                generated.contains(expected),
                "{expected} is missing from the generated uplink schema"
            );
        }
    }
}
