[package]
name = "variegated-instrumentation"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
portable-atomic.workspace = true
defmt = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[features]
default = []
instrumentation = []
