[package]
name = "variegated-soft-pwm"
version = "0.1.0"
edition = "2021"

[lib]
test = false
bench = false

[dependencies]
embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime"] }
defmt = "0.3.8"