[led-resources]
led1 = "embassy_rp::peripherals::PIN_14"
led2 = "embassy_rp::peripherals::PIN_15"

[bootloader-resources]
trigger_pin = "embassy_rp::peripherals::PIN_25"
uart = "embassy_rp::peripherals::UART0"
uart_rx = "embassy_rp::peripherals::PIN_1"
uart_tx = "embassy_rp::peripherals::PIN_0"
flash = "embassy_rp::peripherals::FLASH"