fn main() {
    // `linker_be_nice` re-enters this binary as the linker's error-handling script
    // and `exit`s from there, so nothing that is meant for *cargo* may be printed
    // above it -- it would go to the linker's stdout instead.
    linker_be_nice();

    // `config::ALLOW_TCP_COMMANDS` reads this with `option_env!`, which cargo does
    // *not* track on its own: without this line, setting or clearing the variable
    // leaves a previously-built rlib in place and the toggle appears to do nothing
    // at all -- the most confusing possible failure for a switch whose whole job is
    // to decide whether a network command path exists in the binary.
    //
    // An environment variable rather than argv, and one of only two places in this
    // tree that is allowed: the standing convention is that scripts and fixtures take
    // options on argv, but cargo offers no other channel from an invocation to a
    // `build.rs`/`option_env!` pair. See `config::ALLOW_TCP_COMMANDS`.
    println!("cargo::rerun-if-env-changed=VARIEGATED_DEBUG_ALLOW_TCP_COMMANDS");

    println!("cargo:rustc-link-arg=-Tdefmt.x");
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");

    generate_schemas();
}

/// Regenerate `frontend/src/schemas/schemas.ts` from the Rust wire types.
///
/// Called in-process rather than by shelling out to cargo. The exporter is a *build*
/// dependency, which means cargo compiles it as a host unit -- so it gets std, and it
/// never sees the `-Z build-std` and riscv default target that `.cargo/config.toml`
/// imposes on everything built from this directory. Shelling out would inherit both and
/// fail. (`scripts/generate-schemas.sh` exists for the standalone case and has to work
/// around exactly that.)
///
/// Deliberately no `cargo::rerun-if-changed`. This build script currently emits none, so
/// cargo's default applies: re-run when anything in the package changes. Adding one would
/// *narrow* that, and any file not on the list -- the types live in two other crates --
/// would silently stop triggering regeneration. Cargo already re-runs a build script when
/// its build-dependencies change, which covers the type crates properly.
fn generate_schemas() {
    println!("cargo::rerun-if-env-changed=VARIEGATED_SCHEMA_SKIP");

    // For builds where writing into the source tree is wrong or impossible: a read-only
    // checkout, a sandbox, a packaging run.
    if std::env::var_os("VARIEGATED_SCHEMA_SKIP").is_some() {
        eprintln!("variegated-schema-export: skipped (VARIEGATED_SCHEMA_SKIP is set)");
        return;
    }

    let manifest_dir = std::path::PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"),
    );
    let Some(repo_root) = variegated_schema_export::find_repo_root(&manifest_dir) else {
        eprintln!(
            "variegated-schema-export: no ancestor of {} contains frontend/src; \
             not generating schemas",
            manifest_dir.display()
        );
        return;
    };

    // Everything below goes to stderr. Anything on a build script's stdout starting with
    // `cargo:` is a directive, and modern cargo errors on ones it does not recognize.
    match variegated_schema_export::write_if_changed(&repo_root) {
        Ok(variegated_schema_export::Outcome::Unchanged) => {}
        Ok(variegated_schema_export::Outcome::Written) => {
            // A content change means the committed bundle definitely predates it, which
            // matters because http.rs `include_bytes!`s frontend/dist and that directory
            // is not tracked. Precise rather than mtime-based: it only fires when the
            // generated bytes actually differ.
            println!(
                "cargo::warning=schemas.ts was regenerated; frontend/dist is now stale. \
                 Run `npm run build` in frontend/ before flashing."
            );
        }
        Err(e) => {
            // A failure here means the frontend would be built against a schema that no
            // longer matches the firmware's types, which is the exact failure this
            // generator exists to prevent. Fail the build rather than warn.
            panic!("variegated-schema-export: {e}");
        }
    }
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                "_defmt_timestamp" => {
                    eprintln!();
                    eprintln!("💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`");
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                "esp_rtos_initialized"
                | "esp_rtos_yield_task"
                | "esp_rtos_task_create" => {
                    eprintln!();
                    eprintln!("💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler.");
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!("💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests");
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}
