[package]
name = "variegated-tlc59108"
version = "0.1.0"
edition = "2021"
description = "Async driver for the TI TLC59108 8-bit I2C LED driver"
repository = "https://github.com/variegated-coffee/variegated-rs"
license = "MIT OR Apache-2.0"
keywords = ["embedded", "async", "tlc59108", "led", "i2c"]
categories = ["embedded", "hardware-support", "no-std"]

[lib]
test = false
bench = false

[features]
default = []
defmt = ["dep:defmt"]

[dependencies]
embedded-hal-async.workspace = true
defmt = { workspace = true, optional = true }

[dev-dependencies]
embassy-executor = { workspace = true, features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { workspace = true, features = ["defmt"] }
embassy-rp = { workspace = true, features = ["defmt", "time-driver", "rp235xb"] }
embassy-embedded-hal = { workspace = true, features = ["defmt"] }
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
panic-probe = { workspace = true, features = ["print-defmt"] }