//! The three checksums the SD bus needs, and the bit-shuffling that 4-bit mode implies.
//!
//! # Wire order
//!
//! Everything here consumes or produces bytes in **wire order**, which is what both the
//! read and the write path already have in hand, so no buffer is ever copied just to
//! checksum it. The layout, and the reason it comes out this way:
//!
//! `rd_data` executes `in pins, 4` with the ISR shifting **left** and autopushing at 32.
//! Each nibble therefore enters at the bottom of the ISR and is pushed up by the next, so
//! the *first* nibble on the wire ends up at bits [31:28] of the received word. Storing
//! that word to memory little-endian would reverse it, which is exactly why the read path
//! byte-swaps: after the swap, memory reads back in the order the nibbles arrived.
//!
//! So, in wire order:
//!
//! * byte `i` holds nibble `2i` in bits [7:4] and nibble `2i+1` in bits [3:0];
//! * within a nibble, `DAT0` is bit 0 and `DAT3` is bit 3, because `in pins, 4` puts the
//!   pin at `IN_BASE` in the least significant position;
//! * therefore **data line `k`'s bit stream is bit `k` of each successive nibble**, most
//!   significant first.
//!
//! Each line carries its own independent CRC-16 over its own bit stream. That is the
//! whole reason 4-bit mode needs anything more than [`crc16`].
//!
//! # Provenance
//!
//! [`crc7`] is taken from the `sdio` crate's SPI transport -- same workspace, same
//! authorship.
//!
//! Everything else here is written from the SD Physical Layer Simplified Specification
//! and is **not** a port of SdFat's `crc16()`. That function is a bit-sliced `uint64_t`
//! construction carrying the comment "Modified from `sdio_crc16_4bit_checksum()` in
//! ZuluSCSI-firmware", and ZuluSCSI-firmware is GPL-family -- a licence question relative
//! to this crate's MIT terms that is not ours to resolve. The approach below is a
//! different algorithm reached from the specification: a 256-entry nibble-transpose table
//! feeding a 256-entry byte-wise CRC table. Its correctness rests on published
//! CRC-16/XMODEM vectors and on `crc16_4line_agrees_with_four_independent_crc16s`, which
//! chains the four-line version to the byte-wise one, rather than on agreeing with SdFat.

/// CRC-7 over a command frame, polynomial `x^7 + x^3 + 1` (`0x89`).
///
/// Returns the CRC in the low seven bits; the caller frames it as `(crc << 1) | 1`.
///
/// Bitwise rather than table-driven on purpose: it runs over five bytes per command and
/// fifteen per R2 response, so a 256-entry table would cost more flash than it saves
/// cycles. Identical to the `sdio` crate's, deliberately -- the command frame is the same
/// frame on both transports and the two implementations should not be able to disagree.
pub fn crc7(data: &[u8]) -> u8 {
    let mut crc: u8 = 0;
    for &byte in data {
        crc ^= byte;
        for _ in 0..8 {
            if crc & 0x80 != 0 {
                crc ^= 0x89;
            }
            crc <<= 1;
        }
    }
    crc >> 1
}

/// CRC-16-CCITT byte table: polynomial `x^16 + x^12 + x^5 + 1` (`0x1021`), zero initial
/// value, no reflection, no final inversion.
///
/// Generated by a `const fn` rather than pasted as 256 literals, so the parameters are
/// legible in the source instead of being an opaque block a reader has to trust. The
/// *tests* pin the result against published vectors rather than against this generator --
/// a generator and a table that agree with each other prove nothing, and "some CRC-16" is
/// not good enough here: CRC-16/ARC and CRC-16/MODBUS use a different polynomial and
/// reflect their bits, and either would produce a self-consistent implementation that
/// disagrees with every SD card in existence.
const CRC16_TAB: [u16; 256] = {
    let mut tab = [0u16; 256];
    let mut i = 0;
    while i < 256 {
        let mut crc = (i as u16) << 8;
        let mut bit = 0;
        while bit < 8 {
            crc = if crc & 0x8000 != 0 {
                (crc << 1) ^ 0x1021
            } else {
                crc << 1
            };
            bit += 1;
        }
        tab[i] = crc;
        i += 1;
    }
    tab
};

/// Nibble transpose: one wire byte to four pre-positioned two-bit lane contributions.
///
/// A wire byte carries two nibbles, and each nibble carries one bit for each of the four
/// data lines. So a single byte contributes exactly two bits to each of the four
/// per-line bit streams: bit `k` of the high nibble (earlier on the wire, so more
/// significant) followed by bit `k` of the low nibble.
///
/// `XPOSE[b]` packs all four of those pairs into one `u32`, with lane `k`'s pair already
/// sitting at bits `[8k+1 : 8k]`. That placement is what lets [`crc16_4line`] fold four
/// wire bytes into a single accumulator with four shift-or steps and then read off four
/// finished bytes, instead of running four independent shift chains.
const XPOSE: [u32; 256] = {
    let mut tab = [0u32; 256];
    let mut b = 0usize;
    while b < 256 {
        let mut v = 0u32;
        let mut k = 0;
        while k < 4 {
            // High nibble first: it is the earlier of the two on the wire, so it is the
            // more significant of the pair.
            let pair = (((b >> (4 + k)) & 1) << 1) | ((b >> k) & 1);
            v |= (pair as u32) << (8 * k);
            k += 1;
        }
        tab[b] = v;
        b += 1;
    }
    tab
};

/// Fold one byte into a CRC-16-CCITT accumulator.
#[inline(always)]
const fn step(crc: u16, byte: u8) -> u16 {
    (crc << 8) ^ CRC16_TAB[(((crc >> 8) as u8) ^ byte) as usize]
}

/// CRC-16-CCITT over a byte stream.
///
/// This is the 1-bit-mode data CRC as well as the general-purpose one, and the two are
/// the same function rather than merely similar: on a one-line bus the `DAT0` bit stream
/// *is* the byte stream, most significant bit first, so there is nothing to transpose.
///
/// Note that an all-zero block checksums to zero. That is correct, not a bug -- with a
/// zero initial value and no final inversion, a stream of zero bits never disturbs the
/// register. It is worth knowing because a driver that silently returned an all-zero
/// buffer would also produce a matching CRC and look healthy.
pub fn crc16(data: &[u8]) -> u16 {
    let mut crc = 0u16;
    for &b in data {
        crc = step(crc, b);
    }
    crc
}

/// The four per-line CRC-16s of a 4-bit-mode data block.
///
/// `data` must be in wire order (see the module docs) and its length must be a multiple
/// of four bytes, since four wire bytes are what yield exactly one whole byte for each of
/// the four lines. Every block size the SD protocol asks for here satisfies that: 8 bytes
/// for the SCR, 64 for the SD Status and the CMD6 switch response, 512 for a sector.
///
/// Returned in line order, so `[0]` is `DAT0`.
pub fn crc16_4line(data: &[u8]) -> [u16; 4] {
    assert!(
        data.len().is_multiple_of(4),
        "4-bit data CRC needs a whole number of 4-byte groups"
    );

    let (mut c0, mut c1, mut c2, mut c3) = (0u16, 0u16, 0u16, 0u16);

    for g in data.chunks_exact(4) {
        // Lane k occupies bits [8k+7 : 8k] of the accumulator. Each `<< 2` makes room for
        // one more pair, and four of them fill each lane exactly -- so no lane can ever
        // spill into the next, and no masking is needed on the way out.
        let mut acc = XPOSE[g[0] as usize];
        acc = (acc << 2) | XPOSE[g[1] as usize];
        acc = (acc << 2) | XPOSE[g[2] as usize];
        acc = (acc << 2) | XPOSE[g[3] as usize];

        c0 = step(c0, acc as u8);
        c1 = step(c1, (acc >> 8) as u8);
        c2 = step(c2, (acc >> 16) as u8);
        c3 = step(c3, (acc >> 24) as u8);
    }

    [c0, c1, c2, c3]
}

/// Pack four per-line CRCs into the two words `wr_data` transmits after the payload.
///
/// The CRC field is sixteen nibbles: nibble `j` carries bit `15 - j` of every line's CRC,
/// with `DAT0` at bit 0 as everywhere else. `wr_data` shifts its OSR left from a 32-bit
/// threshold, so the first nibble to go out must sit at bits [31:28] -- these words are
/// pushed to the FIFO as-is, with no byte swap, unlike the payload.
pub fn interleave_crc(crc: &[u16; 4]) -> [u32; 2] {
    let mut words = [0u32; 2];
    for j in 0..16usize {
        let mut nibble = 0u32;
        for (k, &line) in crc.iter().enumerate() {
            nibble |= (((line >> (15 - j)) & 1) as u32) << k;
        }
        words[j / 8] |= nibble << (28 - 4 * (j % 8));
    }
    words
}

/// Recover four per-line CRCs from the two words a 4-bit read clocked in after the data.
///
/// The exact inverse of [`interleave_crc`], and used on the read path against the two
/// trailing words of the transfer.
pub fn deinterleave_crc(words: &[u32; 2]) -> [u16; 4] {
    let mut crc = [0u16; 4];
    for j in 0..16usize {
        let nibble = (words[j / 8] >> (28 - 4 * (j % 8))) & 0xF;
        for (k, line) in crc.iter_mut().enumerate() {
            *line |= (((nibble >> k) & 1) as u16) << (15 - j);
        }
    }
    crc
}

// `needless_range_loop` fires on the table and per-line checks below, where the index is
// not incidental -- it *is* the subject. `for b in 0..256 { XPOSE[b] }` is checking that
// entry `b` encodes byte `b`, and `for k in 0..4 { fast[k] }` is checking that lane `k`
// carries line `k`. Rewritten as `.iter().enumerate()` the assertion no longer names the
// number whose meaning is the point of the test.
#[cfg(test)]
#[allow(clippy::needless_range_loop)]
mod tests {
    use super::*;

    /// The framed CRC byte as it appears on the wire, so these can be compared against
    /// the values quoted in the SD specification.
    fn framed(bytes: &[u8]) -> u8 {
        (crc7(bytes) << 1) | 1
    }

    #[test]
    fn crc7_matches_known_command_vectors() {
        assert_eq!(framed(&[0x40, 0x00, 0x00, 0x00, 0x00]), 0x95); // CMD0
        assert_eq!(framed(&[0x51, 0x00, 0x00, 0x00, 0x00]), 0x55); // CMD17, arg 0
        assert_eq!(framed(&[0x48, 0x00, 0x00, 0x01, 0xAA]), 0x87); // CMD8, arg 0x1AA
    }

    /// Pinned against published vectors rather than against this implementation's own
    /// output. The XMODEM check value is the one that actually constrains the parameters:
    /// get the polynomial, the initial value or the bit order wrong and this fails, where
    /// a round-trip test against ourselves would pass happily.
    #[test]
    fn crc16_matches_known_vectors() {
        assert_eq!(crc16(b"123456789"), 0x31C3);
        assert_eq!(crc16(b"A"), 0x58E5);
        assert_eq!(crc16(&[]), 0x0000);
        // Not a degenerate case being papered over -- see the note on `crc16`.
        assert_eq!(crc16(&[0u8; 512]), 0x0000);
    }

    #[test]
    fn crc16_detects_single_bit_flips() {
        let mut block = [0u8; 512];
        for (i, b) in block.iter_mut().enumerate() {
            *b = (i as u8).wrapping_mul(31).wrapping_add(7);
        }
        let good = crc16(&block);
        for bit in [0usize, 1, 7, 8, 255, 4095] {
            let mut bad = block;
            bad[bit / 8] ^= 1 << (bit % 8);
            assert_ne!(crc16(&bad), good, "flipping bit {bit} went undetected");
        }
    }

    /// The transpose table against the definition it is supposed to encode.
    #[test]
    fn xpose_table_matches_a_naive_reference() {
        for b in 0..256usize {
            let mut want = 0u32;
            for k in 0..4 {
                let hi = (b >> (4 + k)) & 1;
                let lo = (b >> k) & 1;
                want |= (((hi << 1) | lo) as u32) << (8 * k);
            }
            assert_eq!(XPOSE[b], want, "XPOSE[{b}]");
        }
    }

    /// Deinterleave a wire-order block into one line's byte stream, the slow obvious way.
    ///
    /// Deliberately written from the definition in the module docs rather than shared with
    /// [`crc16_4line`]: it is the independent reference the fast path is checked against,
    /// so any cleverness it borrowed would defeat the purpose.
    fn line_stream(data: &[u8], k: usize) -> Vec<u8> {
        let mut bits = Vec::new();
        let mut acc = 0u8;
        let mut n = 0;
        for &byte in data {
            for nibble in [byte >> 4, byte & 0xF] {
                acc = (acc << 1) | ((nibble >> k) & 1);
                n += 1;
                if n == 8 {
                    bits.push(acc);
                    acc = 0;
                    n = 0;
                }
            }
        }
        assert_eq!(n, 0, "line stream did not end on a byte boundary");
        bits
    }

    /// The load-bearing test for an independently written four-line CRC.
    ///
    /// `crc16` is pinned to published vectors above; this chains `crc16_4line` to it by
    /// deinterleaving the same block with a naive reference and checking that each line's
    /// stream, run through the byte-wise implementation, gives the same answer. Without
    /// this, the fast version is only self-consistent.
    #[test]
    fn crc16_4line_agrees_with_four_independent_crc16s() {
        // A cheap deterministic PRNG; the point is a block with no structure a
        // transposition bug could accidentally survive, not cryptographic quality.
        let mut state = 0x1234_5678u32;
        let mut block = [0u8; 512];
        for b in block.iter_mut() {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            *b = (state >> 24) as u8;
        }

        let fast = crc16_4line(&block);
        for k in 0..4 {
            assert_eq!(fast[k], crc16(&line_stream(&block, k)), "line {k}");
        }
    }

    /// The same, at the two other block sizes the protocol actually asks for.
    #[test]
    fn crc16_4line_agrees_at_every_block_size_in_use() {
        for len in [8usize, 64, 512] {
            let mut block = vec![0u8; len];
            for (i, b) in block.iter_mut().enumerate() {
                *b = (i as u8).wrapping_mul(101).wrapping_add(19);
            }
            let fast = crc16_4line(&block);
            for k in 0..4 {
                assert_eq!(fast[k], crc16(&line_stream(&block, k)), "len {len}, line {k}");
            }
        }
    }

    /// When every nibble is 0x0 or 0xF all four lines carry the same bit stream, so all
    /// four CRCs must be equal -- and equal to the byte-wise CRC of that stream. Links
    /// the 4-bit and 1-bit implementations to each other at a point where they must agree.
    #[test]
    fn crc16_4line_degenerates_to_crc16_when_all_lines_carry_one_stream() {
        let pattern: [u8; 8] = [0xF0, 0x0F, 0xFF, 0x00, 0x0F, 0xF0, 0x00, 0xFF];
        let mut block = [0u8; 512];
        for (i, b) in block.iter_mut().enumerate() {
            *b = pattern[i % pattern.len()];
        }

        let fast = crc16_4line(&block);
        assert!(
            fast.iter().all(|&c| c == fast[0]),
            "identical streams gave different CRCs: {fast:04x?}"
        );
        assert_eq!(fast[0], crc16(&line_stream(&block, 0)));
    }

    /// Flipping one line's bit must disturb exactly that line's CRC.
    ///
    /// A whole-block comparison would pass even if the lane indices were rotated or
    /// mirrored; this is what catches that, and a lane mix-up is the single most likely
    /// way to get a transposed CRC subtly wrong.
    #[test]
    fn a_single_bit_flip_changes_exactly_one_line() {
        let mut block = [0u8; 64];
        for (i, b) in block.iter_mut().enumerate() {
            *b = (i as u8).wrapping_mul(37).wrapping_add(5);
        }
        let base = crc16_4line(&block);

        for k in 0..4 {
            // Bit k of the high nibble of byte 9 -- an arbitrary interior nibble.
            let mut bad = block;
            bad[9] ^= 1 << (4 + k);
            let got = crc16_4line(&bad);
            for line in 0..4 {
                if line == k {
                    assert_ne!(got[line], base[line], "flip on line {k} did not change it");
                } else {
                    assert_eq!(got[line], base[line], "flip on line {k} disturbed line {line}");
                }
            }
        }
    }

    #[test]
    fn interleave_crc_round_trips() {
        for crc in [
            [0x0000u16, 0x0000, 0x0000, 0x0000],
            [0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF],
            [0x0001, 0x0002, 0x0004, 0x0008],
            [0x8000, 0x4000, 0x2000, 0x1000],
            [0x31C3, 0x58E5, 0xDEAD, 0xBEEF],
        ] {
            assert_eq!(deinterleave_crc(&interleave_crc(&crc)), crc, "{crc:04x?}");
        }
    }

    /// Pins the nibble layout of the CRC field, not just that it round-trips.
    ///
    /// A CRC of `0x8000` on `DAT0` alone means the very first CRC nibble carries a 1 in
    /// bit 0 and nothing else, i.e. word 0 must be `0x1000_0000`. Round-tripping alone
    /// would accept a consistently mirrored layout that no card would recognise.
    #[test]
    fn interleave_crc_puts_the_first_bit_in_the_first_nibble() {
        assert_eq!(interleave_crc(&[0x8000, 0, 0, 0]), [0x1000_0000, 0]);
        assert_eq!(interleave_crc(&[0, 0, 0, 0x8000]), [0x8000_0000, 0]);
        // The last CRC bit of DAT0 lands in the final nibble of the second word.
        assert_eq!(interleave_crc(&[0x0001, 0, 0, 0]), [0, 0x0000_0001]);
    }

    #[test]
    #[should_panic(expected = "whole number of 4-byte groups")]
    fn crc16_4line_rejects_a_ragged_block() {
        crc16_4line(&[0u8; 6]);
    }
}
