//! # Variegated Postcard TypeScript Type Generator
//!
//! This crate provides tools for generating TypeScript schema definitions from Rust types
//! that are serialized using Postcard. The generated schemas are compatible with the
//! `@variegated-coffee/serde-postcard-ts` library.
//!
//! ## Key Features
//!
//! - **Field Order Preservation**: Maintains exact field order as Postcard serialization is order-dependent
//! - **Type Dependency Resolution**: Automatically orders type definitions based on dependencies
//! - **Full Rust Type Support**: Handles structs, enums (unit, newtype, tuple, struct variants), generics, and more
//!
//! ## Usage
//!
//! ### Deriving PostcardTsTypegen
//!
//! ```ignore
//! use variegated_postcard_ts_typegen::PostcardTsTypegen;
//!
//! #[derive(PostcardTsTypegen)]
//! struct MyStruct {
//!     field1: u32,
//!     field2: String,
//! }
//! ```
//!
//! ### Generating Schema File (in build.rs)
//!
//! ```ignore
//! use variegated_postcard_ts_typegen::SchemaGenerator;
//!
//! fn main() {
//!     let mut generator = SchemaGenerator::new();
//!
//!     // Register types
//!     generator.add::<MyStruct>();
//!     generator.add::<AnotherType>();
//!
//!     // Generate the schema file
//!     generator.write_to_file("schema.ts").unwrap();
//! }
//! ```

pub use variegated_postcard_ts_typegen_derive::PostcardTsTypegen;

mod codegen;
mod primitives;
mod schema;

pub use codegen::*;
pub use schema::*;

use std::any::TypeId;
use std::collections::{HashMap, HashSet};

/// A generator for creating TypeScript schema files from Rust types.
pub struct SchemaGenerator {
    types: HashMap<TypeId, Box<dyn SchemaProvider>>,
    order: Vec<TypeId>,
}

impl SchemaGenerator {
    /// Creates a new schema generator.
    pub fn new() -> Self {
        Self {
            types: HashMap::new(),
            order: Vec::new(),
        }
    }

    /// Adds a type to the generator.
    ///
    /// Types are automatically ordered based on their dependencies to ensure
    /// that dependent types are defined before types that use them.
    pub fn add<T: PostcardTsType + 'static>(&mut self) {
        let type_id = TypeId::of::<T>();
        if self.types.contains_key(&type_id) {
            return;
        }

        let schema = T::generate_schema();
        let provider = ConcreteSchemaProvider {
            schema,
            type_id,
        };

        self.types.insert(type_id, Box::new(provider));
        self.order.push(type_id);
    }

    /// Generates the TypeScript schema file content.
    ///
    /// The types are topologically sorted based on their dependencies to ensure
    /// correct ordering.
    pub fn generate(&self) -> String {
        let mut output = String::new();

        // Add file header
        output.push_str("// AUTO-GENERATED by variegated-postcard-ts-typegen\n");
        output.push_str("// DO NOT EDIT MANUALLY\n");
        output.push_str("//\n");
        output.push_str("// IMPORTANT: Field order in struct schemas matches the Rust struct declaration order exactly.\n");
        output.push_str("// Postcard serialization is order-dependent - fields are serialized/deserialized in declaration order.\n");
        output.push_str("\n");

        // Add imports
        output.push_str("import {\n");
        output.push_str("    string,\n");
        output.push_str("    f32,\n");
        output.push_str("    map,\n");
        output.push_str("    u64,\n");
        output.push_str("    seq,\n");
        output.push_str("    unitVariant,\n");
        output.push_str("    option,\n");
        output.push_str("    u32,\n");
        output.push_str("    struct,\n");
        output.push_str("    newtypeVariant,\n");
        output.push_str("    f64,\n");
        output.push_str("    enumType,\n");
        output.push_str("    bool,\n");
        output.push_str("    tupleVariant,\n");
        output.push_str("    u8,\n");
        output.push_str("    u16,\n");
        output.push_str("    InferType,\n");
        output.push_str("    i8,\n");
        output.push_str("    i16,\n");
        output.push_str("    i32,\n");
        output.push_str("    i64\n");
        output.push_str("} from '@variegated-coffee/serde-postcard-ts';\n\n");

        // Sort types topologically
        let sorted_types = self.topological_sort();

        // Generate schemas
        for type_id in sorted_types {
            if let Some(provider) = self.types.get(&type_id) {
                let schema = provider.get_schema();
                output.push_str(&codegen::generate_ts_schema(&schema));
                output.push_str("\n\n");
            }
        }

        // Generate type exports
        output.push_str("// Type exports\n");
        for type_id in &self.order {
            if let Some(provider) = self.types.get(type_id) {
                let schema = provider.get_schema();
                let rust_name = schema.name.trim_end_matches("Schema");
                output.push_str(&format!(
                    "export type {} = InferType<typeof {}>;\n",
                    rust_name, schema.name
                ));
            }
        }

        output
    }

    /// Writes the generated schema to a file.
    pub fn write_to_file<P: AsRef<std::path::Path>>(&self, path: P) -> std::io::Result<()> {
        std::fs::write(path, self.generate())
    }

    /// Performs a topological sort of the types based on their dependencies.
    fn topological_sort(&self) -> Vec<TypeId> {
        let mut sorted = Vec::new();
        let mut visited = HashSet::new();
        let mut temp_mark = HashSet::new();

        for &type_id in &self.order {
            if !visited.contains(&type_id) {
                self.visit(type_id, &mut visited, &mut temp_mark, &mut sorted);
            }
        }

        sorted
    }

    fn visit(
        &self,
        type_id: TypeId,
        visited: &mut HashSet<TypeId>,
        temp_mark: &mut HashSet<TypeId>,
        sorted: &mut Vec<TypeId>,
    ) {
        if visited.contains(&type_id) {
            return;
        }

        if temp_mark.contains(&type_id) {
            // Circular dependency - just skip for now
            return;
        }

        temp_mark.insert(type_id);

        // Visit dependencies first
        if let Some(provider) = self.types.get(&type_id) {
            let deps = provider.get_dependencies();
            for dep_id in deps {
                if self.types.contains_key(&dep_id) {
                    self.visit(dep_id, visited, temp_mark, sorted);
                }
            }
        }

        temp_mark.remove(&type_id);
        visited.insert(type_id);
        sorted.push(type_id);
    }
}

impl Default for SchemaGenerator {
    fn default() -> Self {
        Self::new()
    }
}

trait SchemaProvider {
    fn get_schema(&self) -> &SchemaDefinition;
    fn get_dependencies(&self) -> Vec<TypeId>;
}

struct ConcreteSchemaProvider {
    schema: SchemaDefinition,
    #[allow(dead_code)]
    type_id: TypeId,
}

impl SchemaProvider for ConcreteSchemaProvider {
    fn get_schema(&self) -> &SchemaDefinition {
        &self.schema
    }

    fn get_dependencies(&self) -> Vec<TypeId> {
        // For now, return empty - we'll rely on declaration order
        // In the future, we could analyze the schema to extract actual dependencies
        Vec::new()
    }
}
