// @generated by variegated-schema-export -- DO NOT EDIT.
//
// Runtime postcard schema descriptors, generated from the Rust types so they cannot
// drift from them. Field order and enum variant order ARE the wire format: postcard is
// non-self-describing, so a field out of order silently mis-decodes everything after
// it. That is why this file is no longer written by hand.
//
// Source of truth:
//   variegated-rs/variegated-controller-types      (Status, Configuration, ...)
//   variegated-rs/variegated-control-algorithm     (PidParameters, PidTerm, Limits)
//   crates/variegated-comms-api-types              (WsMessage, RoutineStorage, Set*Request)
//
// To regenerate:  scripts/generate-schemas.sh
// It also runs from variegated-comms-firmware's build.rs, so a normal firmware build
// keeps this file current.
//
// `usize` is deliberately absent. serde encodes it as u64 regardless of target width,
// but this producer is 32-bit, where u32 and u64 varints are identical for every value
// it can emit -- so a round-trip test could not tell a wrong choice from a right one.
// The generator refuses `usize` outright; wire-facing indices are declared u32 in Rust.
//
// Hand-written additions belong in epilogue.ts.in, which is appended below verbatim.

import {
  InferType,
  bool,
  enumType,
  f32,
  i8,
  map,
  newtypeVariant,
  option,
  seq,
  string,
  struct,
  structVariant,
  tuple,
  tupleVariant,
  u16,
  u32,
  u64,
  u8,
  unitVariant
} from '@variegated-coffee/serde-postcard-ts';

export const ActuatorCapabilitySchema = enumType('ActuatorCapability', {
  HeatingElement: unitVariant('HeatingElement'),
  Pump: unitVariant('Pump'),
  SolenoidValve: unitVariant('SolenoidValve'),
  ThreeWayValve: unitVariant('ThreeWayValve'),
  WaterMixer: unitVariant('WaterMixer'),
  ScaleTare: unitVariant('ScaleTare')
});

export const BluetoothDriverKindSchema = enumType('BluetoothDriverKind', {
  BelkaPortal: unitVariant('BelkaPortal'),
  AcaiaOld: unitVariant('AcaiaOld')
});

export const BoilerControlModeSchema = enumType('BoilerControlMode', {
  Temperature: unitVariant('Temperature'),
  Pressure: unitVariant('Pressure'),
  Off: unitVariant('Off')
});

export const BoilerControlTargetValuesSchema = struct({
  target_temperature: f32(),
  target_pressure: f32()
});

export const BoilerControlTargetValuesUpdateSchema = struct({
  temperature: option(f32()),
  pressure: option(f32())
});

export const BoilerTypeSchema = enumType('BoilerType', {
  BrewBoiler: unitVariant('BrewBoiler'),
  SteamBoiler: unitVariant('SteamBoiler'),
  VirtualSteamBoiler: unitVariant('VirtualSteamBoiler')
});

export const ControlCurveSchema = struct({
  a: f32(),
  b: f32(),
  c: f32(),
  min: f32(),
  max: f32()
});

export const ControlModeCapabilitySchema = enumType('ControlModeCapability', {
  TemperaturePid: unitVariant('TemperaturePid'),
  PressurePid: unitVariant('PressurePid'),
  FlowRatePid: unitVariant('FlowRatePid'),
  OutputFlowRatePid: unitVariant('OutputFlowRatePid'),
  FixedDutyCycle: unitVariant('FixedDutyCycle'),
  FullOn: unitVariant('FullOn'),
  Off: unitVariant('Off')
});

export const DerivedFormulaSchema = enumType('DerivedFormula', {
  Linear: structVariant('Linear', {
    base_param: u8(),
    multiplier: f32(),
    offset: f32()
  }),
  Sum: structVariant('Sum', {
    params: seq(u8())
  }),
  Difference: structVariant('Difference', {
    param_a: u8(),
    param_b: u8()
  }),
  Product: structVariant('Product', {
    params: seq(u8())
  })
});

export const DurationSchema = struct({
  secs: u64(),
  nanos: u32()
});

export const EnvironmentalSensorTypeSchema = enumType('EnvironmentalSensorType', {
  AmbientTemperature: unitVariant('AmbientTemperature'),
  CaseTemperature: unitVariant('CaseTemperature'),
  ExternalTemperature: unitVariant('ExternalTemperature'),
  Humidity: unitVariant('Humidity')
});

export const GroupBrewControlModeSchema = enumType('GroupBrewControlMode', {
  GroupFlowRate: unitVariant('GroupFlowRate'),
  GroupFlowRateCurve: unitVariant('GroupFlowRateCurve'),
  Pressure: unitVariant('Pressure'),
  PressureCurve: unitVariant('PressureCurve'),
  OutputFlowRate: unitVariant('OutputFlowRate'),
  OutputFlowRateCurve: unitVariant('OutputFlowRateCurve'),
  FixedDutyCycle: unitVariant('FixedDutyCycle'),
  FixedDutyCycleCurve: unitVariant('FixedDutyCycleCurve'),
  FullOn: unitVariant('FullOn'),
  Off: unitVariant('Off')
});

export const HeatingElementContentionStrategySchema = enumType('HeatingElementContentionStrategy', {
  BrewPriority: unitVariant('BrewPriority'),
  SteamPriority: unitVariant('SteamPriority'),
  Proportional: unitVariant('Proportional')
});

export const ImprovStateSchema = enumType('ImprovState', {
  Stopped: unitVariant('Stopped'),
  AwaitingAuthorization: unitVariant('AwaitingAuthorization'),
  Authorized: unitVariant('Authorized'),
  Provisioning: unitVariant('Provisioning'),
  Provisioned: unitVariant('Provisioned')
});

export const KalmanParametersSchema = struct({
  process_noise: f32(),
  measurement_noise: f32(),
  estimated_error: f32(),
  posterior_estimate: f32()
});

export const LimitsSchema = struct({
  lower: f32(),
  upper: f32()
});

export const MachineConfigurationSchema = struct({
  heating_element_interlock: bool(),
  max_shot_logs: u32(),
  log_sample_decimation: u8(),
  prevent_start_on_empty_tank: bool(),
  allow_continue_on_empty_tank: bool()
});

export const MachineModeSchema = enumType('MachineMode', {
  On: unitVariant('On'),
  Off: unitVariant('Off'),
  PowerSaveStandby: unitVariant('PowerSaveStandby')
});

export const ParameterUnitSchema = enumType('ParameterUnit', {
  Seconds: unitVariant('Seconds'),
  Celsius: unitVariant('Celsius'),
  Bar: unitVariant('Bar'),
  MillilitersPerSecond: unitVariant('MillilitersPerSecond'),
  Grams: unitVariant('Grams'),
  Percent: unitVariant('Percent'),
  Milliliters: unitVariant('Milliliters'),
  MillisiemensPerCentimeter: unitVariant('MillisiemensPerCentimeter'),
  ExtractionRate: unitVariant('ExtractionRate'),
  ExtractedSolids: unitVariant('ExtractedSolids')
});

export const ParameterValueSchema = enumType('ParameterValue', {
  Static: newtypeVariant('Static', f32()),
  Parameter: newtypeVariant('Parameter', u8()),
  DerivedParameter: newtypeVariant('DerivedParameter', u8())
});

export const PeripheralTypeSchema = enumType('PeripheralType', {
  Scale: unitVariant('Scale'),
  PressureSensor: unitVariant('PressureSensor'),
  FlowMeter: unitVariant('FlowMeter'),
  LevelSensor: unitVariant('LevelSensor'),
  BrewSensor: unitVariant('BrewSensor')
});

export const PidOutSchema = struct({
  p: f32(),
  i: f32(),
  d: f32(),
  out: f32(),
  acting_kp: f32(),
  acting_ki: f32(),
  acting_kd: f32()
});

export const PidParameterTargetSchema = enumType('PidParameterTarget', {
  BoilerTemperature: newtypeVariant('BoilerTemperature', u8()),
  BoilerPressure: newtypeVariant('BoilerPressure', u8()),
  GroupFlowRate: newtypeVariant('GroupFlowRate', u8()),
  GroupOutputFlowRate: newtypeVariant('GroupOutputFlowRate', u8()),
  GroupPressure: newtypeVariant('GroupPressure', u8())
});

export const PumpConfigurationSchema = struct({
  tacho_pulses_per_liter: option(f32()),
  max_duty_cycle: option(u8()),
  min_duty_cycle: option(u8()),
  ramp_up_time_ms: option(u32()),
  ramp_down_time_ms: option(u32())
});

export const RoutineIndexSchema = enumType('RoutineIndex', {
  Internal: newtypeVariant('Internal', u32()),
  Function: newtypeVariant('Function', u32()),
  Custom: newtypeVariant('Custom', u32())
});

export const RoutineStepExitTypeSchema = enumType('RoutineStepExitType', {
  NextStep: unitVariant('NextStep'),
  JumpToStep: newtypeVariant('JumpToStep', u32()),
  Finished: unitVariant('Finished')
});

export const RoutineTypeSchema = enumType('RoutineType', {
  HeatUp: unitVariant('HeatUp'),
  UserDefined: unitVariant('UserDefined'),
  Cleaning: unitVariant('Cleaning'),
  HardwareButtonMapped: unitVariant('HardwareButtonMapped')
});

export const RoutineWriteErrorSchema = enumType('RoutineWriteError', {
  TooLarge: unitVariant('TooLarge'),
  Malformed: unitVariant('Malformed'),
  Immutable: unitVariant('Immutable'),
  Storage: unitVariant('Storage'),
  UnsupportedVersion: unitVariant('UnsupportedVersion')
});

export const ScaleSelectorSchema = enumType('ScaleSelector', {
  GroupScale: newtypeVariant('GroupScale', u8())
});

export const ScheduleTriggerSchema = struct({
  on_minute: u8(),
  on_hour: u8(),
  on_days: option(seq(string())),
  on_date: option(string()),
  enabled: bool(),
  once: bool()
});

export const SensorCapabilitySchema = enumType('SensorCapability', {
  Temperature: unitVariant('Temperature'),
  Pressure: unitVariant('Pressure'),
  WaterLevel: unitVariant('WaterLevel'),
  InputFlowRate: unitVariant('InputFlowRate'),
  OutputFlowRate: unitVariant('OutputFlowRate'),
  Weight: unitVariant('Weight'),
  ElectricalConductivity: unitVariant('ElectricalConductivity')
});

export const ShotAnnotationKeySchema = enumType('ShotAnnotationKey', {
  DoseWeight: unitVariant('DoseWeight'),
  Beans: unitVariant('Beans'),
  GrindSize: unitVariant('GrindSize'),
  Other: newtypeVariant('Other', string())
});

export const ShotAnnotationValueSchema = enumType('ShotAnnotationValue', {
  Number: newtypeVariant('Number', f32()),
  Text: newtypeVariant('Text', string())
});

export const ShotLogDayFilterSchema = enumType('ShotLogDayFilter', {
  All: unitVariant('All'),
  Day: newtypeVariant('Day', u32()),
  Undated: unitVariant('Undated')
});

export const ShotLogIdSchema = struct({
  day: option(u32()),
  time: u32()
});

export const ShotLogStorageErrorSchema = enumType('ShotLogStorageError', {
  CardNotPresent: unitVariant('CardNotPresent'),
  NotExfat: unitVariant('NotExfat'),
  ReadError: unitVariant('ReadError'),
  WriteError: unitVariant('WriteError'),
  SerializationError: unitVariant('SerializationError'),
  CrcError: unitVariant('CrcError'),
  NotFound: unitVariant('NotFound'),
  DirectoryError: unitVariant('DirectoryError'),
  BusUnavailable: unitVariant('BusUnavailable'),
  UnsupportedVersion: unitVariant('UnsupportedVersion'),
  OperationTimedOut: unitVariant('OperationTimedOut')
});

export const ShotStateSchema = enumType('ShotState', {
  HeadspaceFill: unitVariant('HeadspaceFill'),
  Saturation: unitVariant('Saturation'),
  PostFirstDrop: unitVariant('PostFirstDrop')
});

export const ShotUploadConfigSchema = struct({
  endpoint: option(string()),
  token: option(string()),
  enabled: bool(),
  server_key: option(string()),
  device_key: option(string())
});

export const ShotUploadKeyUpdateSchema = enumType('ShotUploadKeyUpdate', {
  Keep: unitVariant('Keep'),
  Clear: unitVariant('Clear'),
  Set: newtypeVariant('Set', string())
});

export const ShotUploadTokenUpdateSchema = enumType('ShotUploadTokenUpdate', {
  Keep: unitVariant('Keep'),
  Clear: unitVariant('Clear'),
  Set: newtypeVariant('Set', string())
});

export const ShotUploadViewSchema = struct({
  endpoint: option(string()),
  enabled: bool(),
  token_set: bool(),
  server_key: option(string()),
  device_key_set: bool()
});

export const SteamWandConfigurationSchema = struct({
  temperature_target: option(f32()),
  openness: option(u8()),
  purge_time_seconds: option(u32()),
  max_steam_time_seconds: option(u32()),
  auto_purge_enabled: bool(),
  supply_tank_index: option(u8())
});

export const SteamWandStatusSchema = struct({
  is_steaming: bool(),
  valve_openness: u8()
});

export const TankStatusSchema = struct({
  water_level: option(u8())
});

export const WaterDispersalPumpStrategySchema = enumType('WaterDispersalPumpStrategy', {
  AlwaysPump: newtypeVariant('AlwaysPump', u8()),
  NoPump: unitVariant('NoPump')
});

export const WaterTapStatusSchema = struct({
  is_dispensing: bool()
});

export const WifiCredentialsSchema = struct({
  ssid: string(),
  password: string()
});

export const WirelessConnectionStatusSchema = struct({
  connected: bool(),
  rssi: option(i8())
});

export const BluetoothPeripheralAssociationSchema = struct({
  id: u16(),
  address: tuple(u8(), u8(), u8(), u8(), u8(), u8()),
  address_random: bool(),
  driver: BluetoothDriverKindSchema,
  enabled: bool(),
  name: string()
});

export const BoilerControlStateSchema = struct({
  mode: BoilerControlModeSchema,
  values: BoilerControlTargetValuesSchema
});

export const BoilerDefinitionSchema = struct({
  name: string(),
  boiler_type: BoilerTypeSchema,
  sensors: seq(SensorCapabilitySchema),
  actuators: seq(ActuatorCapabilitySchema),
  control_modes: seq(ControlModeCapabilitySchema),
  has_fill_mechanism: bool()
});

export const BrewControlTargetSchema = struct({
  mode: GroupBrewControlModeSchema,
  value: f32()
});

export const BrewStatusSchema = struct({
  brew_time: DurationSchema,
  brew_input_volume: option(f32()),
  shot_state: option(ShotStateSchema),
  extracted_solids: option(f32()),
  output_volume: option(f32())
});

export const CommsStatusSchema = struct({
  timestamp: option(u64()),
  wifi_connected: bool(),
  wifi_rssi: option(i8()),
  peripheral_connection_status: map(u16(), WirelessConnectionStatusSchema),
  improv: ImprovStateSchema,
  sntp_sync_seq: u32(),
  wifi_ssid: string(),
  wifi_ip: option(tuple(u8(), u8(), u8(), u8()))
});

export const DerivedParameterSchema = struct({
  index: u8(),
  name: string(),
  unit: option(ParameterUnitSchema),
  formula: DerivedFormulaSchema
});

export const DiscoveredBluetoothPeripheralSchema = struct({
  address: tuple(u8(), u8(), u8(), u8(), u8(), u8()),
  address_random: bool(),
  name: string(),
  rssi: i8(),
  suggested_driver: option(BluetoothDriverKindSchema)
});

export const EnvironmentalSensorDefinitionSchema = struct({
  name: string(),
  sensor_type: EnvironmentalSensorTypeSchema,
  measurement_range: option(tuple(f32(), f32()))
});

export const FillConfigurationSchema = struct({
  fill_threshold: option(u8()),
  pump_configuration: option(PumpConfigurationSchema)
});

export const GroupBrewControlTargetValuesSchema = struct({
  flow_rate: f32(),
  flow_rate_curve: ControlCurveSchema,
  pressure: f32(),
  pressure_curve: ControlCurveSchema,
  output_flow_rate: f32(),
  output_flow_rate_curve: ControlCurveSchema,
  duty_cycle: u8(),
  duty_cycle_curve: ControlCurveSchema
});

export const GroupBrewControlTargetValuesUpdateSchema = struct({
  flow_rate: option(f32()),
  flow_rate_curve: option(ControlCurveSchema),
  pressure: option(f32()),
  pressure_curve: option(ControlCurveSchema),
  output_flow_rate: option(f32()),
  output_flow_rate_curve: option(ControlCurveSchema),
  duty_cycle: option(u8()),
  duty_cycle_curve: option(ControlCurveSchema)
});

export const GroupDefinitionSchema = struct({
  name: string(),
  sensors: seq(SensorCapabilitySchema),
  actuators: seq(ActuatorCapabilitySchema),
  control_modes: seq(ControlModeCapabilitySchema)
});

export const OutputSchema = enumType('Output', {
  Off: unitVariant('Off'),
  FixedDutyCycle: newtypeVariant('FixedDutyCycle', u8()),
  PidOutput: newtypeVariant('PidOutput', PidOutSchema)
});

export const PeripheralDefinitionSchema = struct({
  peripheral_type: PeripheralTypeSchema,
  location: string(),
  capabilities: seq(SensorCapabilitySchema),
  support_calibration: bool(),
  via_comms_mcu: bool()
});

export const PeripheralInfoSchema = struct({
  peripheral_type: PeripheralTypeSchema,
  is_available: bool()
});

export const PidTermSchema = struct({
  positive_scale: f32(),
  negative_scale: f32(),
  limits: LimitsSchema
});

export const PreviousBrewInfoSchema = struct({
  brew_time: DurationSchema,
  brew_input_volume: option(f32()),
  output_weight: option(f32()),
  started_at_millis: u64(),
  stopped_at_millis: u64()
});

export const QueryErrorSchema = enumType('QueryError', {
  NotFound: unitVariant('NotFound'),
  Unavailable: unitVariant('Unavailable'),
  RoutineWrite: newtypeVariant('RoutineWrite', RoutineWriteErrorSchema),
  ShotLogStorage: newtypeVariant('ShotLogStorage', ShotLogStorageErrorSchema)
});

export const RoutineExecutionStatusSchema = struct({
  routine_index: RoutineIndexSchema,
  current_step: option(u32()),
  step_elapsed_time: option(DurationSchema),
  total_elapsed_time: option(DurationSchema),
  resolved_parameters: map(u8(), f32())
});

export const RoutineParameterSchema = struct({
  index: u8(),
  name: string(),
  default: f32(),
  unit: option(ParameterUnitSchema),
  linked_attribute: option(ShotAnnotationKeySchema)
});

export const RoutinePrerequisiteSchema = struct({
  capability: SensorCapabilitySchema
});

export const ScheduleActionSchema = enumType('ScheduleAction', {
  RunRoutine: tupleVariant('RunRoutine', RoutineIndexSchema, option(map(u8(), f32()))),
  CancelRoutine: unitVariant('CancelRoutine'),
  SetMachineMode: newtypeVariant('SetMachineMode', MachineModeSchema),
  SetBoilerControlTarget: tupleVariant('SetBoilerControlTarget', u8(), BoilerControlModeSchema, option(BoilerControlTargetValuesUpdateSchema)),
  SetBoilerControlTargetValues: tupleVariant('SetBoilerControlTargetValues', u8(), BoilerControlTargetValuesUpdateSchema)
});

export const ShotAnnotationSchema = struct({
  key: ShotAnnotationKeySchema,
  value: ShotAnnotationValueSchema
});

export const ShotLogListRequestSchema = struct({
  limit: u16(),
  before: option(ShotLogIdSchema),
  day: ShotLogDayFilterSchema
});

export const ShotUploadSettingsSchema = struct({
  endpoint: option(string()),
  enabled: bool(),
  token: ShotUploadTokenUpdateSchema,
  server_key: option(string()),
  device_key: ShotUploadKeyUpdateSchema
});

export const StateConditionSchema = enumType('StateCondition', {
  Brewing: newtypeVariant('Brewing', u8()),
  NotBrewing: newtypeVariant('NotBrewing', u8()),
  BoilerTemperatureAbove: tupleVariant('BoilerTemperatureAbove', u8(), ParameterValueSchema),
  BoilerTemperatureBelow: tupleVariant('BoilerTemperatureBelow', u8(), ParameterValueSchema),
  BoilerPressureAbove: tupleVariant('BoilerPressureAbove', u8(), ParameterValueSchema),
  BoilerPressureBelow: tupleVariant('BoilerPressureBelow', u8(), ParameterValueSchema),
  GroupInputFlowRateAbove: tupleVariant('GroupInputFlowRateAbove', u8(), ParameterValueSchema),
  GroupInputFlowRateBelow: tupleVariant('GroupInputFlowRateBelow', u8(), ParameterValueSchema),
  GroupPressureAbove: tupleVariant('GroupPressureAbove', u8(), ParameterValueSchema),
  GroupPressureBelow: tupleVariant('GroupPressureBelow', u8(), ParameterValueSchema),
  WaterTapFlowRateAbove: tupleVariant('WaterTapFlowRateAbove', u8(), ParameterValueSchema),
  WaterTapFlowRateBelow: tupleVariant('WaterTapFlowRateBelow', u8(), ParameterValueSchema),
  OutputWeightAbove: tupleVariant('OutputWeightAbove', u8(), ParameterValueSchema),
  OutputWeightBelow: tupleVariant('OutputWeightBelow', u8(), ParameterValueSchema),
  InputVolumeAboveRelativeToStart: tupleVariant('InputVolumeAboveRelativeToStart', u8(), ParameterValueSchema),
  GroupOutputConductivityAbove: tupleVariant('GroupOutputConductivityAbove', u8(), ParameterValueSchema),
  GroupOutputConductivityBelow: tupleVariant('GroupOutputConductivityBelow', u8(), ParameterValueSchema),
  GroupExtractionRateAbove: tupleVariant('GroupExtractionRateAbove', u8(), ParameterValueSchema),
  GroupExtractionRateBelow: tupleVariant('GroupExtractionRateBelow', u8(), ParameterValueSchema),
  ExtractedSolidsAbove: tupleVariant('ExtractedSolidsAbove', u8(), ParameterValueSchema),
  ExtractedSolidsBelow: tupleVariant('ExtractedSolidsBelow', u8(), ParameterValueSchema),
  ShotStateReached: tupleVariant('ShotStateReached', u8(), ShotStateSchema)
});

export const SteamWandDefinitionSchema = struct({
  name: string(),
  sensors: seq(SensorCapabilitySchema),
  actuators: seq(ActuatorCapabilitySchema),
  control_modes: seq(ControlModeCapabilitySchema)
});

export const TankConfigurationSchema = struct({
  low_level_warning_threshold: option(u8()),
  water_level_sensor_kalman_parameters: option(KalmanParametersSchema),
  empty_threshold: option(u8())
});

export const TankDefinitionSchema = struct({
  name: string(),
  sensors: seq(SensorCapabilitySchema)
});

export const TransitionOriginSchema = enumType('TransitionOrigin', {
  Value: newtypeVariant('Value', ParameterValueSchema),
  CurrentTarget: unitVariant('CurrentTarget'),
  CurrentValue: unitVariant('CurrentValue')
});

export const WaterTapConfigurationSchema = struct({
  pump_strategy: WaterDispersalPumpStrategySchema,
  temperature_target: option(f32()),
  max_dispense_time_seconds: option(u32()),
  flow_rate_limit: option(f32()),
  pump_configuration: option(PumpConfigurationSchema),
  supply_tank_index: option(u8())
});

export const WaterTapDefinitionSchema = struct({
  name: string(),
  sensors: seq(SensorCapabilitySchema),
  actuators: seq(ActuatorCapabilitySchema),
  control_modes: seq(ControlModeCapabilitySchema)
});

export const BluetoothScanStatusSchema = struct({
  scanning: bool(),
  blocked: bool(),
  reports_dropped: u16(),
  discovered: seq(DiscoveredBluetoothPeripheralSchema)
});

export const BluetoothScanUpdateSchema = enumType('BluetoothScanUpdate', {
  Discovered: newtypeVariant('Discovered', DiscoveredBluetoothPeripheralSchema),
  Finished: structVariant('Finished', {
    reports_dropped: u16()
  })
});

export const BoilerStatusSchema = struct({
  temperature: option(f32()),
  pressure: option(f32()),
  water_level: option(u8()),
  output: OutputSchema,
  control_state: BoilerControlStateSchema
});

export const ClientQuerySchema = enumType('ClientQuery', {
  RoutineDefinition: newtypeVariant('RoutineDefinition', RoutineIndexSchema),
  WriteRoutine: structVariant('WriteRoutine', {
    index: option(RoutineIndexSchema),
    routine: seq(u8())
  }),
  ShotLogPage: newtypeVariant('ShotLogPage', ShotLogListRequestSchema)
});

export const GroupBrewControlStateSchema = struct({
  mode: GroupBrewControlModeSchema,
  values: GroupBrewControlTargetValuesSchema
});

export const MachineDefinitionSchema = struct({
  name: string(),
  boilers: map(u8(), BoilerDefinitionSchema),
  groups: map(u8(), GroupDefinitionSchema),
  water_taps: map(u8(), WaterTapDefinitionSchema),
  tanks: map(u8(), TankDefinitionSchema),
  steam_wands: map(u8(), SteamWandDefinitionSchema),
  environmental_sensors: map(u8(), EnvironmentalSensorDefinitionSchema),
  peripherals: map(u16(), PeripheralDefinitionSchema),
  function_routines: map(u32(), string())
});

export const PeripheralStatusSchema = struct({
  peripherals: map(u16(), PeripheralInfoSchema)
});

export const PidParametersSchema = struct({
  kp: PidTermSchema,
  ki: PidTermSchema,
  kd: PidTermSchema
});

export const RoutineCommandSchema = enumType('RoutineCommand', {
  StartBrewing: newtypeVariant('StartBrewing', u8()),
  StopBrewing: newtypeVariant('StopBrewing', u8()),
  TareGroupScale: newtypeVariant('TareGroupScale', u8()),
  StartPumpingToWaterTap: newtypeVariant('StartPumpingToWaterTap', u8()),
  StopPumpingToWaterTap: newtypeVariant('StopPumpingToWaterTap', u8()),
  StartSteaming: newtypeVariant('StartSteaming', u8()),
  StopSteaming: newtypeVariant('StopSteaming', u8()),
  SetSteamValveOpenness: tupleVariant('SetSteamValveOpenness', u8(), ParameterValueSchema),
  SetBoilerTemperature: tupleVariant('SetBoilerTemperature', u8(), ParameterValueSchema),
  SetBoilerPressure: tupleVariant('SetBoilerPressure', u8(), ParameterValueSchema),
  SetGroupFlowRate: tupleVariant('SetGroupFlowRate', u8(), ParameterValueSchema),
  SetGroupPressure: tupleVariant('SetGroupPressure', u8(), ParameterValueSchema),
  SetGroupOutputFlowRate: tupleVariant('SetGroupOutputFlowRate', u8(), ParameterValueSchema),
  SetGroupFixedDutyCycle: tupleVariant('SetGroupFixedDutyCycle', u8(), ParameterValueSchema),
  SetGroupFullOn: newtypeVariant('SetGroupFullOn', u8()),
  SetGroupOff: newtypeVariant('SetGroupOff', u8()),
  SetBoilerOff: newtypeVariant('SetBoilerOff', u8()),
  SetGroupFlowRateWithTransition: tupleVariant('SetGroupFlowRateWithTransition', u8(), ParameterValueSchema, ParameterValueSchema, TransitionOriginSchema),
  SetGroupPressureWithTransition: tupleVariant('SetGroupPressureWithTransition', u8(), ParameterValueSchema, ParameterValueSchema, TransitionOriginSchema),
  SetGroupOutputFlowRateWithTransition: tupleVariant('SetGroupOutputFlowRateWithTransition', u8(), ParameterValueSchema, ParameterValueSchema, TransitionOriginSchema),
  SetGroupFixedDutyCycleWithTransition: tupleVariant('SetGroupFixedDutyCycleWithTransition', u8(), ParameterValueSchema, ParameterValueSchema, TransitionOriginSchema),
  InferGroupPressureIntegral: tupleVariant('InferGroupPressureIntegral', u8(), ParameterValueSchema),
  InferGroupFlowRateIntegral: tupleVariant('InferGroupFlowRateIntegral', u8(), ParameterValueSchema),
  InferGroupOutputFlowRateIntegral: tupleVariant('InferGroupOutputFlowRateIntegral', u8(), ParameterValueSchema)
});

export const RoutineExitConditionSchema = enumType('RoutineExitCondition', {
  Always: unitVariant('Always'),
  Never: unitVariant('Never'),
  After: newtypeVariant('After', ParameterValueSchema),
  AfterDurationRelativeToStart: newtypeVariant('AfterDurationRelativeToStart', ParameterValueSchema),
  StateConditionMet: newtypeVariant('StateConditionMet', StateConditionSchema),
  UserAction: newtypeVariant('UserAction', u8())
});

export const RoutineSummarySchema = struct({
  routine_type: RoutineTypeSchema,
  name: string(),
  step_count: u16(),
  parameter_count: u8(),
  derived_parameter_count: u8(),
  finally_count: u8(),
  prerequisites: seq(RoutinePrerequisiteSchema)
});

export const ScheduleItemSchema = struct({
  trigger_at: ScheduleTriggerSchema,
  commands: seq(ScheduleActionSchema)
});

export const ShotAnnotationsSchema = struct({
  entries: seq(ShotAnnotationSchema),
  tasting_notes: option(string())
});

export const BoilerConfigurationSchema = struct({
  temperature_pid_parameters: PidParametersSchema,
  pressure_pid_parameters: PidParametersSchema,
  control_state: BoilerControlStateSchema,
  max_temperature: option(f32()),
  max_pressure: option(f32()),
  temperature_sensor_kalman_parameters: option(KalmanParametersSchema),
  pressure_sensor_kalman_parameters: option(KalmanParametersSchema),
  fill_config: option(FillConfigurationSchema),
  supply_tank_index: option(u8()),
  minimum_safe_level: option(u8())
});

export const GroupConfigurationSchema = struct({
  flow_rate_pid_parameters: PidParametersSchema,
  output_flow_rate_pid_parameters: PidParametersSchema,
  pressure_pid_parameters: PidParametersSchema,
  brew_control_state: GroupBrewControlStateSchema,
  max_brew_time_seconds: option(u32()),
  auto_tare_enabled: bool(),
  pump_configuration: option(PumpConfigurationSchema),
  pressure_sensor_kalman_parameters: option(KalmanParametersSchema),
  flow_sensor_pulses_per_liter: option(f32()),
  supply_tank_index: option(u8())
});

export const GroupStatusSchema = struct({
  is_brewing: bool(),
  three_way_valve_open: option(bool()),
  current_brew: option(BrewStatusSchema),
  input_flow_rate: option(f32()),
  input_volume: option(f32()),
  output_flow_rate: option(f32()),
  output_weight: option(f32()),
  pressure: option(f32()),
  temperature: option(f32()),
  output_temperature: option(f32()),
  output_electrical_conductivity: option(f32()),
  extraction_rate: option(f32()),
  pump_output: OutputSchema,
  control_state: GroupBrewControlStateSchema,
  previous_brew: option(PreviousBrewInfoSchema),
  pump_rpm: option(f32()),
  brew_control_target: option(BrewControlTargetSchema)
});

export const RoutineExitSchema = struct({
  condition: RoutineExitConditionSchema,
  then: RoutineStepExitTypeSchema,
  description: option(string())
});

export const RoutineSummaryStorageSchema = struct({
  internal: map(u32(), RoutineSummarySchema),
  function: map(u32(), RoutineSummarySchema),
  custom: map(u32(), RoutineSummarySchema)
});

export const ShotLogListEntrySchema = struct({
  id: ShotLogIdSchema,
  size_bytes: u32(),
  annotations: ShotAnnotationsSchema
});

export const ConfigurationSchema = struct({
  machine_config: MachineConfigurationSchema,
  boiler_configurations: map(u8(), BoilerConfigurationSchema),
  group_configurations: map(u8(), GroupConfigurationSchema),
  water_tap_configurations: map(u8(), WaterTapConfigurationSchema),
  tank_configurations: map(u8(), TankConfigurationSchema),
  steam_wand_configurations: map(u8(), SteamWandConfigurationSchema),
  schedules: seq(ScheduleItemSchema),
  bluetooth_peripherals: seq(BluetoothPeripheralAssociationSchema),
  shot_upload: ShotUploadViewSchema
});

export const RoutineStepSchema = struct({
  entry_command: seq(RoutineCommandSchema),
  exits: seq(RoutineExitSchema),
  description: option(string())
});

export const ShotLogEventSchema = enumType('ShotLogEvent', {
  Stored: newtypeVariant('Stored', ShotLogListEntrySchema),
  Deleted: newtypeVariant('Deleted', ShotLogIdSchema)
});

export const ShotLogListSchema = struct({
  entries: seq(ShotLogListEntrySchema),
  truncated: bool()
});

export const StatusSchema = struct({
  boiler_statuses: map(u8(), BoilerStatusSchema),
  group_statuses: map(u8(), GroupStatusSchema),
  water_tap_statuses: map(u8(), WaterTapStatusSchema),
  steam_wand_statuses: map(u8(), SteamWandStatusSchema),
  tank_statuses: map(u8(), TankStatusSchema),
  mode: MachineModeSchema,
  routine_execution: option(RoutineExecutionStatusSchema),
  comms_status: option(CommsStatusSchema),
  comms_status_age: option(DurationSchema),
  peripheral_status: PeripheralStatusSchema,
  current_local_time: option(string()),
  bluetooth: BluetoothScanStatusSchema,
  pending_shot_annotations: ShotAnnotationsSchema,
  sd_card_present: option(bool())
});

export const QueryOkSchema = enumType('QueryOk', {
  RoutineDefinition: newtypeVariant('RoutineDefinition', seq(u8())),
  RoutineStored: newtypeVariant('RoutineStored', RoutineIndexSchema),
  ShotLogPage: newtypeVariant('ShotLogPage', ShotLogListSchema)
});

export const RoutineSchema = struct({
  version: u16(),
  routine_type: RoutineTypeSchema,
  name: string(),
  parameters: seq(RoutineParameterSchema),
  derived_parameters: seq(DerivedParameterSchema),
  steps: seq(RoutineStepSchema),
  finally: seq(RoutineCommandSchema),
  prerequisites: seq(RoutinePrerequisiteSchema),
  shot_annotations: seq(ShotAnnotationSchema)
});

export const MachineCommandSchema = enumType('MachineCommand', {
  StartBrewing: newtypeVariant('StartBrewing', u8()),
  StopBrewing: newtypeVariant('StopBrewing', u8()),
  StartPumpingToWaterTap: newtypeVariant('StartPumpingToWaterTap', u8()),
  StopPumpingToWaterTap: newtypeVariant('StopPumpingToWaterTap', u8()),
  StartSteaming: newtypeVariant('StartSteaming', u8()),
  StopSteaming: newtypeVariant('StopSteaming', u8()),
  SetSteamValveOpenness: tupleVariant('SetSteamValveOpenness', u8(), u8()),
  SetBoilerControlTarget: tupleVariant('SetBoilerControlTarget', u8(), BoilerControlModeSchema, option(BoilerControlTargetValuesUpdateSchema)),
  SetBoilerControlTargetValues: tupleVariant('SetBoilerControlTargetValues', u8(), BoilerControlTargetValuesUpdateSchema),
  SetGroupBrewControlTarget: tupleVariant('SetGroupBrewControlTarget', u8(), GroupBrewControlModeSchema, option(GroupBrewControlTargetValuesUpdateSchema)),
  SetGroupBrewControlTargetValues: tupleVariant('SetGroupBrewControlTargetValues', u8(), GroupBrewControlTargetValuesUpdateSchema),
  SetPidParameters: tupleVariant('SetPidParameters', PidParameterTargetSchema, PidParametersSchema),
  RunRoutine: tupleVariant('RunRoutine', RoutineIndexSchema, option(map(u8(), f32()))),
  CancelRoutine: unitVariant('CancelRoutine'),
  EnableBoiler: newtypeVariant('EnableBoiler', u8()),
  DisableBoiler: newtypeVariant('DisableBoiler', u8()),
  TareGroupScale: newtypeVariant('TareGroupScale', u8()),
  ZeroCalibrateGroupScale: newtypeVariant('ZeroCalibrateGroupScale', u8()),
  CalibrateGroupScale100g: newtypeVariant('CalibrateGroupScale100g', u8()),
  UpdateCommsStatus: newtypeVariant('UpdateCommsStatus', CommsStatusSchema),
  AddScheduleItem: newtypeVariant('AddScheduleItem', ScheduleItemSchema),
  RemoveScheduleItem: newtypeVariant('RemoveScheduleItem', u32()),
  UpdateScheduleItem: tupleVariant('UpdateScheduleItem', u32(), ScheduleItemSchema),
  AddRoutine: newtypeVariant('AddRoutine', RoutineSchema),
  RemoveRoutine: newtypeVariant('RemoveRoutine', RoutineIndexSchema),
  UpdateRoutine: tupleVariant('UpdateRoutine', RoutineIndexSchema, RoutineSchema),
  SetMachineMode: newtypeVariant('SetMachineMode', MachineModeSchema),
  OptimizeConfigurationStorage: unitVariant('OptimizeConfigurationStorage'),
  OptimizeRoutineStorage: unitVariant('OptimizeRoutineStorage'),
  OptimizeScheduleStorage: unitVariant('OptimizeScheduleStorage'),
  SetGroupPumpConfiguration: tupleVariant('SetGroupPumpConfiguration', u8(), PumpConfigurationSchema),
  SetWaterTapPumpConfiguration: tupleVariant('SetWaterTapPumpConfiguration', u8(), PumpConfigurationSchema),
  SetFillPumpConfiguration: tupleVariant('SetFillPumpConfiguration', u8(), PumpConfigurationSchema),
  InferGroupPressureIntegral: tupleVariant('InferGroupPressureIntegral', u8(), f32()),
  InferGroupFlowRateIntegral: tupleVariant('InferGroupFlowRateIntegral', u8(), f32()),
  InferGroupOutputFlowRateIntegral: tupleVariant('InferGroupOutputFlowRateIntegral', u8(), f32()),
  SetHeatingElementInterlock: newtypeVariant('SetHeatingElementInterlock', bool()),
  SetHeatingElementContentionStrategy: newtypeVariant('SetHeatingElementContentionStrategy', HeatingElementContentionStrategySchema),
  SetWaterDispersalPumpStrategy: tupleVariant('SetWaterDispersalPumpStrategy', u8(), WaterDispersalPumpStrategySchema),
  AssociateBluetoothPeripheral: newtypeVariant('AssociateBluetoothPeripheral', BluetoothPeripheralAssociationSchema),
  RemoveBluetoothPeripheral: newtypeVariant('RemoveBluetoothPeripheral', u16()),
  SetBluetoothPeripheralEnabled: tupleVariant('SetBluetoothPeripheralEnabled', u16(), bool()),
  ScanForBluetoothPeripherals: unitVariant('ScanForBluetoothPeripherals'),
  UpdateBluetoothScan: newtypeVariant('UpdateBluetoothScan', BluetoothScanUpdateSchema),
  SetShotAnnotations: tupleVariant('SetShotAnnotations', ShotLogIdSchema, ShotAnnotationsSchema),
  SetPendingShotAnnotations: newtypeVariant('SetPendingShotAnnotations', ShotAnnotationsSchema),
  TagDoseFromScale: newtypeVariant('TagDoseFromScale', ScaleSelectorSchema),
  OpenWifiProvisioningWindow: structVariant('OpenWifiProvisioningWindow', {
    duration_ms: u32()
  }),
  CloseWifiProvisioningWindow: unitVariant('CloseWifiProvisioningWindow'),
  SetWifiCredentials: newtypeVariant('SetWifiCredentials', WifiCredentialsSchema),
  IdentifyMachine: unitVariant('IdentifyMachine'),
  RequestConfiguration: unitVariant('RequestConfiguration'),
  DeleteShotLog: newtypeVariant('DeleteShotLog', ShotLogIdSchema),
  SetShotUploadConfig: newtypeVariant('SetShotUploadConfig', ShotUploadConfigSchema),
  SetShotUploadSettings: newtypeVariant('SetShotUploadSettings', ShotUploadSettingsSchema)
});

export const QueryOutcomeSchema = enumType('QueryOutcome', {
  Ok: newtypeVariant('Ok', QueryOkSchema),
  Failed: newtypeVariant('Failed', QueryErrorSchema)
});

export const WsMessageSchema = enumType('WsMessage', {
  StatusUpdate: newtypeVariant('StatusUpdate', StatusSchema),
  ConfigurationUpdate: newtypeVariant('ConfigurationUpdate', ConfigurationSchema),
  MachineDefinition: newtypeVariant('MachineDefinition', MachineDefinitionSchema),
  RoutinesUpdate: newtypeVariant('RoutinesUpdate', RoutineSummaryStorageSchema),
  CommandAck: structVariant('CommandAck', {
    id: u32(),
    success: bool(),
    error: option(string())
  }),
  RequestMachineDefinition: unitVariant('RequestMachineDefinition'),
  RequestRoutines: unitVariant('RequestRoutines'),
  SendMachineCommand: newtypeVariant('SendMachineCommand', MachineCommandSchema),
  RequestConfiguration: unitVariant('RequestConfiguration'),
  ShotLogEvent: newtypeVariant('ShotLogEvent', ShotLogEventSchema),
  SendMachineCommandWithId: structVariant('SendMachineCommandWithId', {
    id: u32(),
    command: MachineCommandSchema
  }),
  Query: structVariant('Query', {
    id: u32(),
    query: ClientQuerySchema
  }),
  QueryReply: structVariant('QueryReply', {
    id: u32(),
    outcome: QueryOutcomeSchema
  })
});

export type ShotLogList = InferType<typeof ShotLogListSchema>;
export type Status = InferType<typeof StatusSchema>;
export type Configuration = InferType<typeof ConfigurationSchema>;
export type MachineDefinition = InferType<typeof MachineDefinitionSchema>;
export type RoutineSummaryStorage = InferType<typeof RoutineSummaryStorageSchema>;
export type WsMessage = InferType<typeof WsMessageSchema>;
export type MachineCommand = InferType<typeof MachineCommandSchema>;
export type Routine = InferType<typeof RoutineSchema>;
export type RoutineIndex = InferType<typeof RoutineIndexSchema>;
export type ActuatorCapability = InferType<typeof ActuatorCapabilitySchema>;
export type BluetoothDriverKind = InferType<typeof BluetoothDriverKindSchema>;
export type BluetoothPeripheralAssociation = InferType<typeof BluetoothPeripheralAssociationSchema>;
export type BluetoothScanStatus = InferType<typeof BluetoothScanStatusSchema>;
export type BluetoothScanUpdate = InferType<typeof BluetoothScanUpdateSchema>;
export type BoilerConfiguration = InferType<typeof BoilerConfigurationSchema>;
export type BoilerControlMode = InferType<typeof BoilerControlModeSchema>;
export type BoilerControlState = InferType<typeof BoilerControlStateSchema>;
export type BoilerControlTargetValues = InferType<typeof BoilerControlTargetValuesSchema>;
export type BoilerControlTargetValuesUpdate = InferType<typeof BoilerControlTargetValuesUpdateSchema>;
export type BoilerDefinition = InferType<typeof BoilerDefinitionSchema>;
export type BoilerStatus = InferType<typeof BoilerStatusSchema>;
export type BoilerType = InferType<typeof BoilerTypeSchema>;
export type BrewControlTarget = InferType<typeof BrewControlTargetSchema>;
export type BrewStatus = InferType<typeof BrewStatusSchema>;
export type ClientQuery = InferType<typeof ClientQuerySchema>;
export type CommsStatus = InferType<typeof CommsStatusSchema>;
export type ControlCurve = InferType<typeof ControlCurveSchema>;
export type ControlModeCapability = InferType<typeof ControlModeCapabilitySchema>;
export type DerivedFormula = InferType<typeof DerivedFormulaSchema>;
export type DerivedParameter = InferType<typeof DerivedParameterSchema>;
export type DiscoveredBluetoothPeripheral = InferType<typeof DiscoveredBluetoothPeripheralSchema>;
export type Duration = InferType<typeof DurationSchema>;
export type EnvironmentalSensorDefinition = InferType<typeof EnvironmentalSensorDefinitionSchema>;
export type EnvironmentalSensorType = InferType<typeof EnvironmentalSensorTypeSchema>;
export type FillConfiguration = InferType<typeof FillConfigurationSchema>;
export type GroupBrewControlMode = InferType<typeof GroupBrewControlModeSchema>;
export type GroupBrewControlState = InferType<typeof GroupBrewControlStateSchema>;
export type GroupBrewControlTargetValues = InferType<typeof GroupBrewControlTargetValuesSchema>;
export type GroupBrewControlTargetValuesUpdate = InferType<typeof GroupBrewControlTargetValuesUpdateSchema>;
export type GroupConfiguration = InferType<typeof GroupConfigurationSchema>;
export type GroupDefinition = InferType<typeof GroupDefinitionSchema>;
export type GroupStatus = InferType<typeof GroupStatusSchema>;
export type HeatingElementContentionStrategy = InferType<typeof HeatingElementContentionStrategySchema>;
export type ImprovState = InferType<typeof ImprovStateSchema>;
export type KalmanParameters = InferType<typeof KalmanParametersSchema>;
export type Limits = InferType<typeof LimitsSchema>;
export type MachineConfiguration = InferType<typeof MachineConfigurationSchema>;
export type MachineMode = InferType<typeof MachineModeSchema>;
export type Output = InferType<typeof OutputSchema>;
export type ParameterUnit = InferType<typeof ParameterUnitSchema>;
export type ParameterValue = InferType<typeof ParameterValueSchema>;
export type PeripheralDefinition = InferType<typeof PeripheralDefinitionSchema>;
export type PeripheralInfo = InferType<typeof PeripheralInfoSchema>;
export type PeripheralStatus = InferType<typeof PeripheralStatusSchema>;
export type PeripheralType = InferType<typeof PeripheralTypeSchema>;
export type PidOut = InferType<typeof PidOutSchema>;
export type PidParameterTarget = InferType<typeof PidParameterTargetSchema>;
export type PidParameters = InferType<typeof PidParametersSchema>;
export type PidTerm = InferType<typeof PidTermSchema>;
export type PreviousBrewInfo = InferType<typeof PreviousBrewInfoSchema>;
export type PumpConfiguration = InferType<typeof PumpConfigurationSchema>;
export type QueryError = InferType<typeof QueryErrorSchema>;
export type QueryOk = InferType<typeof QueryOkSchema>;
export type QueryOutcome = InferType<typeof QueryOutcomeSchema>;
export type RoutineCommand = InferType<typeof RoutineCommandSchema>;
export type RoutineExecutionStatus = InferType<typeof RoutineExecutionStatusSchema>;
export type RoutineExit = InferType<typeof RoutineExitSchema>;
export type RoutineExitCondition = InferType<typeof RoutineExitConditionSchema>;
export type RoutineParameter = InferType<typeof RoutineParameterSchema>;
export type RoutinePrerequisite = InferType<typeof RoutinePrerequisiteSchema>;
export type RoutineStep = InferType<typeof RoutineStepSchema>;
export type RoutineStepExitType = InferType<typeof RoutineStepExitTypeSchema>;
export type RoutineSummary = InferType<typeof RoutineSummarySchema>;
export type RoutineType = InferType<typeof RoutineTypeSchema>;
export type RoutineWriteError = InferType<typeof RoutineWriteErrorSchema>;
export type ScaleSelector = InferType<typeof ScaleSelectorSchema>;
export type ScheduleAction = InferType<typeof ScheduleActionSchema>;
export type ScheduleItem = InferType<typeof ScheduleItemSchema>;
export type ScheduleTrigger = InferType<typeof ScheduleTriggerSchema>;
export type SensorCapability = InferType<typeof SensorCapabilitySchema>;
export type ShotAnnotation = InferType<typeof ShotAnnotationSchema>;
export type ShotAnnotationKey = InferType<typeof ShotAnnotationKeySchema>;
export type ShotAnnotationValue = InferType<typeof ShotAnnotationValueSchema>;
export type ShotAnnotations = InferType<typeof ShotAnnotationsSchema>;
export type ShotLogDayFilter = InferType<typeof ShotLogDayFilterSchema>;
export type ShotLogEvent = InferType<typeof ShotLogEventSchema>;
export type ShotLogId = InferType<typeof ShotLogIdSchema>;
export type ShotLogListEntry = InferType<typeof ShotLogListEntrySchema>;
export type ShotLogListRequest = InferType<typeof ShotLogListRequestSchema>;
export type ShotLogStorageError = InferType<typeof ShotLogStorageErrorSchema>;
export type ShotState = InferType<typeof ShotStateSchema>;
export type ShotUploadConfig = InferType<typeof ShotUploadConfigSchema>;
export type ShotUploadKeyUpdate = InferType<typeof ShotUploadKeyUpdateSchema>;
export type ShotUploadSettings = InferType<typeof ShotUploadSettingsSchema>;
export type ShotUploadTokenUpdate = InferType<typeof ShotUploadTokenUpdateSchema>;
export type ShotUploadView = InferType<typeof ShotUploadViewSchema>;
export type StateCondition = InferType<typeof StateConditionSchema>;
export type SteamWandConfiguration = InferType<typeof SteamWandConfigurationSchema>;
export type SteamWandDefinition = InferType<typeof SteamWandDefinitionSchema>;
export type SteamWandStatus = InferType<typeof SteamWandStatusSchema>;
export type TankConfiguration = InferType<typeof TankConfigurationSchema>;
export type TankDefinition = InferType<typeof TankDefinitionSchema>;
export type TankStatus = InferType<typeof TankStatusSchema>;
export type TransitionOrigin = InferType<typeof TransitionOriginSchema>;
export type WaterDispersalPumpStrategy = InferType<typeof WaterDispersalPumpStrategySchema>;
export type WaterTapConfiguration = InferType<typeof WaterTapConfigurationSchema>;
export type WaterTapDefinition = InferType<typeof WaterTapDefinitionSchema>;
export type WaterTapStatus = InferType<typeof WaterTapStatusSchema>;
export type WifiCredentials = InferType<typeof WifiCredentialsSchema>;
export type WirelessConnectionStatus = InferType<typeof WirelessConnectionStatusSchema>;

// Appended verbatim to the end of the generated schemas.ts. Hand-maintained.
//
// These are UI conveniences with no protocol meaning: names for the entry tuples you
// get from iterating a Map, used by MachineContext. They are not generated because
// deriving `BoilerEntry` from the field name `boilers` would mean putting a
// pluralization rule inside a code generator, and the names are chosen for readability
// rather than derived from anything.
//
// The generator checks that every type referenced here is one it actually emits, so a
// rename upstream fails the build with a clear message instead of a puzzling tsc error.

// Map entry type aliases for proper typing in components
export type BoilerEntry = [number, BoilerDefinition];
export type GroupEntry = [number, GroupDefinition];
export type WaterTapEntry = [number, WaterTapDefinition];
export type SteamWandEntry = [number, SteamWandDefinition];
export type TankEntry = [number, TankDefinition];
export type BoilerStatusEntry = [number, BoilerStatus];
export type GroupStatusEntry = [number, GroupStatus];
export type WaterTapStatusEntry = [number, WaterTapStatus];
export type SteamWandStatusEntry = [number, SteamWandStatus];
export type RoutineEntry = [number, Routine];
export type PeripheralEntry = [number, PeripheralDefinition];
