[package]
name = "variegated-controller-types"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
defmt = { workspace = true, optional = true }
heapless.workspace = true
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"], optional = true }
variegated-control-algorithm = { version = "0.1.0", path = "../variegated-control-algorithm", features = ["defmt"] }
sequential-storage = { workspace = true, optional = true, features = ["defmt-03"] }
postcard = { workspace = true, optional = true, features = ["alloc", "use-crc"] }
crc = { workspace = true, optional = true }

[features]
serde = ["dep:serde", "variegated-control-algorithm/serde", "serde/derive", "heapless/serde"]
std = []
defmt = ["dep:defmt", "heapless/defmt-03"]
double_boiler = []
single_boiler = []
single_group = []
sequential-storage = ["dep:sequential-storage", "dep:postcard", "dep:crc", "serde"]
default = ["serde", "defmt", "double_boiler", "single_group"]