[package]
name = "variegated-log"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
defmt.workspace = true
defmt-rtt.workspace = true
log.workspace = true
embassy-executor = { workspace = true, features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-usb-logger.workspace = true
embassy-rp = { workspace = true, features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"] }

[features]
default = []
rp2040 = ["embassy-rp/rp2040"]
rp235xa = ["embassy-rp/rp235xa"]
rp235xb = ["embassy-rp/rp235xb"]