[internal_spi_bus_peripherals]
spi = "embassy_rp::peripherals::SPI1"
sclk_pin = "embassy_rp::peripherals::PIN_30"
mosi_pin = "embassy_rp::peripherals::PIN_31"
miso_pin = "embassy_rp::peripherals::PIN_28"
dma_tx = "embassy_rp::peripherals::DMA_CH0"
dma_rx = "embassy_rp::peripherals::DMA_CH1"

[internal_i2c_bus_peripherals]
i2c = "embassy_rp::peripherals::I2C1"
scl_pin = "embassy_rp::peripherals::PIN_39"
sda_pin = "embassy_rp::peripherals::PIN_38"

[ads124s08_peripherals]
pin_drdy = "embassy_rp::peripherals::PIN_29"
pin_cs = "embassy_rp::peripherals::PIN_32"

[esp32_peripherals]
uart = "embassy_rp::peripherals::UART1"
tx_pin = "embassy_rp::peripherals::PIN_8"
rx_pin = "embassy_rp::peripherals::PIN_9"
cts_pin = "embassy_rp::peripherals::PIN_10"
rts_pin = "embassy_rp::peripherals::PIN_11"
dma_tx = "embassy_rp::peripherals::DMA_CH4"
dma_rx = "embassy_rp::peripherals::DMA_CH5"

[potentiometer_peripherals]
adc = "embassy_rp::peripherals::ADC"
pin_linear_encoder_a = "embassy_rp::peripherals::PIN_47"

[gear_pump_peripherals]
pwm_speed = "embassy_rp::peripherals::PWM_SLICE10"
pin_speed = "embassy_rp::peripherals::PIN_44"
pwm_tacho_out = "embassy_rp::peripherals::PWM_SLICE4"
pin_tacho_out = "embassy_rp::peripherals::PIN_25"
pin_dir = "embassy_rp::peripherals::PIN_35"
dma_tacho = "embassy_rp::peripherals::DMA_CH9"

[steam_solenoid_peripherals]
pin_steam_solenoid = "embassy_rp::peripherals::PIN_5"
pwm = "embassy_rp::peripherals::PWM_SLICE2"

[rotary_pump_peripherals]
pin_rotary_pump_enable = "embassy_rp::peripherals::PIN_34"

[pulse_counter_pio_peripherals]
pio = "embassy_rp::peripherals::PIO0"

[flow_meter_peripherals]
pwm_flow_meter = "embassy_rp::peripherals::PWM_SLICE3"
pin_flow_meter = "embassy_rp::peripherals::PIN_23"
dma = "embassy_rp::peripherals::DMA_CH8"

[mechanism_peripherals]
pin_brew_he = "embassy_rp::peripherals::PIN_37"
pin_service_he = "embassy_rp::peripherals::PIN_36"
pin_group_solenoid = "embassy_rp::peripherals::PIN_26"
pin_fill_solenoid = "embassy_rp::peripherals::PIN_33"
pin_water_dispersal_solenoid = "embassy_rp::peripherals::PIN_24"

[sd_card_peripherals]
pin_cs = "embassy_rp::peripherals::PIN_41"
pin_det = "embassy_rp::peripherals::PIN_42"

[qwiic_i2c_bus_peripherals]
i2c = "embassy_rp::peripherals::I2C0"
scl_pin = "embassy_rp::peripherals::PIN_17"
sda_pin = "embassy_rp::peripherals::PIN_16"

[eyespi_display_peripherals]
spi = "embassy_rp::peripherals::SPI0"
sclk_pin = "embassy_rp::peripherals::PIN_2"
mosi_pin = "embassy_rp::peripherals::PIN_3"
miso_pin = "embassy_rp::peripherals::PIN_4"
dc_pin = "embassy_rp::peripherals::PIN_6"
reset_pin = "embassy_rp::peripherals::PIN_7"
disp_cs_pin = "embassy_rp::peripherals::PIN_12"
dma_tx = "embassy_rp::peripherals::DMA_CH6"
dma_rx = "embassy_rp::peripherals::DMA_CH7"

[button_mux_peripherals]
pin_interrupt = "embassy_rp::peripherals::PIN_20"

[settings_flash_peripherals]
pin_cs = "embassy_rp::peripherals::PIN_27"

[watchdog_peripherals]
watchdog = "embassy_rp::peripherals::WATCHDOG"

[backlight_peripherals]
pwm = "embassy_rp::peripherals::PWM_SLICE0"
pin = "embassy_rp::peripherals::PIN_1"

[irq_aliases]
EspIrq = "UART1_IRQ"
AdcIrq = "ADC_IRQ_FIFO"
InternalI2cIrq = "I2C1_IRQ"
QwiicI2cIrq = "I2C0_IRQ"
FlowMeterPioIrq = "PIO0_IRQ_0"
DmaIrq = "DMA_IRQ_0"
