//! Impls for types this crate does not define.
//!
//! Everything here is a type with no field *names* that could be wrong -- primitives,
//! containers, and a couple of foreign types whose serde representation is fixed and
//! verifiable from serde's own source. Structs with named fields are deliberately
//! absent: see the note on [`PostcardSchema`](crate::PostcardSchema) about hand-written
//! impls being invisible to a byte-level round-trip check.
//!
//! Each non-obvious mapping below cites the serde or upstream source it was checked
//! against, because "what does serde actually do here" is the entire correctness
//! question and it is not always what the Rust type suggests.

use alloc::boxed::Box;
use alloc::collections::{BTreeMap, BTreeSet};
use alloc::string::String;
use alloc::vec::Vec;

use crate::{Def, Node, PostcardSchema, Registry, TypeId};

macro_rules! primitive {
    ($($ty:ty => $node:ident),* $(,)?) => {
        $(
            impl PostcardSchema for $ty {
                fn node(_reg: &mut Registry) -> Node {
                    Node::$node
                }
            }
        )*
    };
}

primitive! {
    bool => Bool,
    i8 => I8, i16 => I16, i32 => I32, i64 => I64, i128 => I128,
    u8 => U8, u16 => U16, u32 => U32, u64 => U64, u128 => U128,
    f32 => F32, f64 => F64,
    char => Char,
    str => Str,
    String => Str,
}

// serde_core/src/ser/impls.rs:28 -- `primitive_impl!(usize, serialize_u64 as u64)`.
// Width-independent: `usize` is u64 in the data model on every target. Kept as its own
// node so the consumer must make a deliberate decision rather than inheriting a guess.
impl PostcardSchema for usize {
    fn node(_reg: &mut Registry) -> Node {
        Node::Usize
    }
}

impl PostcardSchema for isize {
    fn node(_reg: &mut Registry) -> Node {
        Node::Isize
    }
}

impl PostcardSchema for () {
    fn node(_reg: &mut Registry) -> Node {
        Node::Unit
    }
}

impl<T: PostcardSchema + ?Sized> PostcardSchema for &T {
    fn type_id() -> Option<TypeId> {
        T::type_id()
    }
    fn register(reg: &mut Registry) {
        T::register(reg);
    }
    fn node(reg: &mut Registry) -> Node {
        T::node(reg)
    }
}

impl<T: PostcardSchema + ?Sized> PostcardSchema for Box<T> {
    fn type_id() -> Option<TypeId> {
        T::type_id()
    }
    fn register(reg: &mut Registry) {
        T::register(reg);
    }
    fn node(reg: &mut Registry) -> Node {
        T::node(reg)
    }
}

impl<T: PostcardSchema> PostcardSchema for Option<T> {
    fn node(reg: &mut Registry) -> Node {
        Node::Option(Box::new(T::node(reg)))
    }
}

// `Vec<u8>` maps to a sequence of u8, NOT to `Bytes`. serde's blanket
// `impl Serialize for [T]` calls `serialize_seq`; only an explicit
// `serialize_bytes` (via `serde_bytes` or a manual impl) produces a byte string.
// Postcard happens to encode both identically, so this choice is invisible on the
// wire -- but it is visible in the generated TypeScript type, where the difference is
// `number[]` versus `Uint8Array`.
impl<T: PostcardSchema> PostcardSchema for Vec<T> {
    fn node(reg: &mut Registry) -> Node {
        Node::Seq(Box::new(T::node(reg)))
    }
}

impl<T: PostcardSchema> PostcardSchema for [T] {
    fn node(reg: &mut Registry) -> Node {
        Node::Seq(Box::new(T::node(reg)))
    }
}

// serde_core/src/ser/impls.rs:145-171 -- arrays go through `serialize_tuple($len)`,
// generated by `array_impls!` for N in 1..=32 only.
//
// This is the mapping most likely to be got wrong, and it fails loudly when it is: a
// tuple has NO length prefix, so reaching for `Seq` (or `Bytes`) here would insert a
// spurious varint and shift every subsequent field. `[u8; 6]` is six bytes, not seven.
impl<T: PostcardSchema, const N: usize> PostcardSchema for [T; N] {
    fn node(reg: &mut Registry) -> Node {
        let inner = T::node(reg);
        Node::Tuple(alloc::vec![inner; N])
    }
}

impl<K: PostcardSchema, V: PostcardSchema> PostcardSchema for BTreeMap<K, V> {
    fn node(reg: &mut Registry) -> Node {
        Node::Map { key: Box::new(K::node(reg)), value: Box::new(V::node(reg)) }
    }
}

impl<T: PostcardSchema> PostcardSchema for BTreeSet<T> {
    fn node(reg: &mut Registry) -> Node {
        Node::Seq(Box::new(T::node(reg)))
    }
}

macro_rules! tuple {
    ($($name:ident),+) => {
        impl<$($name: PostcardSchema),+> PostcardSchema for ($($name,)+) {
            fn node(reg: &mut Registry) -> Node {
                Node::Tuple(alloc::vec![$($name::node(reg)),+])
            }
        }
    };
}

tuple!(A);
tuple!(A, B);
tuple!(A, B, C);
tuple!(A, B, C, D);
tuple!(A, B, C, D, E);
tuple!(A, B, C, D, E, F);
tuple!(A, B, C, D, E, F, G);
tuple!(A, B, C, D, E, F, G, H);
tuple!(A, B, C, D, E, F, G, H, I);
tuple!(A, B, C, D, E, F, G, H, I, J);
tuple!(A, B, C, D, E, F, G, H, I, J, K);
tuple!(A, B, C, D, E, F, G, H, I, J, K, L);

// serde_core/src/ser/impls.rs:685-696 -- `serialize_struct("Duration", 2)` with
// `secs` from `as_secs()` (u64) and `nanos` from `subsec_nanos()` (u32).
//
// Named rather than inlined, so it keeps a single shared definition in the output the
// way the hand-written schema had it.
impl PostcardSchema for core::time::Duration {
    fn type_id() -> Option<TypeId> {
        Some(TypeId { module: "core::time", ident: "Duration", args: Vec::new() })
    }

    fn register(reg: &mut Registry) {
        let id = Self::type_id().unwrap();
        if !reg.begin(id.clone()) {
            return;
        }
        let def = Def::Struct(alloc::vec![("secs", Node::U64), ("nanos", Node::U32)]);
        reg.finish(id, def);
    }

    fn node(reg: &mut Registry) -> Node {
        let id = Self::type_id().unwrap();
        Self::register(reg);
        reg.reference(id)
    }
}

// heapless 0.9.3, src/ser.rs. Implemented on the generic types so the `Fnv*` aliases
// (index_map.rs:70, index_set.rs:49) are covered without naming them.
#[cfg(feature = "heapless")]
mod heapless_impls {
    use super::*;

    // src/ser.rs:112 -- `serialize_map`.
    impl<K: PostcardSchema, V: PostcardSchema, S, const N: usize> PostcardSchema
        for heapless::index_map::IndexMap<K, V, S, N>
    {
        fn node(reg: &mut Registry) -> Node {
            Node::Map { key: Box::new(K::node(reg)), value: Box::new(V::node(reg)) }
        }
    }

    // src/ser.rs:44 -- `serialize_seq`, not a set. The data model has no set concept
    // and the TypeScript vocabulary has no set combinator; a set is a sequence that
    // happens to be unique. `Option<FnvIndexSet<Weekday, 8>>` on `ScheduleTrigger` is
    // the only user in this tree.
    impl<T: PostcardSchema, S, const N: usize> PostcardSchema
        for heapless::index_set::IndexSet<T, S, N>
    {
        fn node(reg: &mut Registry) -> Node {
            Node::Seq(Box::new(T::node(reg)))
        }
    }

    // src/ser.rs:60 -- `serialize_seq`.
    //
    // Written against the `Vec<T, N>` alias (vec/mod.rs:277) with its default
    // `LenT = usize` rather than against `VecInner`, which is what every use in this
    // tree looks like. A non-default `LenT` would be a compile error here rather than
    // a wrong schema.
    impl<T: PostcardSchema, const N: usize> PostcardSchema for heapless::Vec<T, N> {
        fn node(reg: &mut Registry) -> Node {
            Node::Seq(Box::new(T::node(reg)))
        }
    }

    // src/ser.rs:144 -- `serialize_str`. The capacity is a Rust-side bound only; it
    // does not appear on the wire, so `String<32>` and `String<96>` are both `Str`.
    impl<const N: usize> PostcardSchema for heapless::String<N> {
        fn node(_reg: &mut Registry) -> Node {
            Node::Str
        }
    }
}

// chrono 0.4.45. Every one of these serializes via `collect_str` with NO
// `is_human_readable` branch anywhere in the crate, so they are strings even in a
// binary format. Postcard implements `collect_str` (src/ser/serializer.rs:321) with the
// same encoding as `serialize_str`, so this holds in no_std.
//
// Checked individually rather than assumed, because "binary format therefore compact
// timestamp" is the natural guess and it is wrong:
//   Weekday       -- weekday.rs:275          -> "Mon".."Sun"
//   NaiveDateTime -- naive/datetime/serde.rs -> "2015-09-05T23:56:04"
//   NaiveDate     -- naive/date/mod.rs       -> "2015-09-05"
//   NaiveTime     -- naive/time/serde.rs     -> "23:56:04"
//   DateTime<Tz>  -- datetime/serde.rs       -> RFC3339
#[cfg(feature = "chrono")]
mod chrono_impls {
    use super::*;

    macro_rules! chrono_str {
        ($($ty:ty),* $(,)?) => {
            $(
                impl PostcardSchema for $ty {
                    fn node(_reg: &mut Registry) -> Node {
                        Node::Str
                    }
                }
            )*
        };
    }

    chrono_str!(
        chrono::NaiveDateTime,
        chrono::NaiveDate,
        chrono::NaiveTime,
        chrono::Weekday,
        chrono::Month,
    );

    impl<Tz: chrono::TimeZone> PostcardSchema for chrono::DateTime<Tz> {
        fn node(_reg: &mut Registry) -> Node {
            Node::Str
        }
    }
}
