#!/usr/bin/env python3
"""Extract the exFAT up-case table from a reference volume into a Rust constant.

The exFAT up-case table maps every UTF-16 code unit to its uppercase form, and it is what
makes filename matching case-insensitive on the volume. Every formatter has to write one.

**This is extracted from a real volume rather than written out by hand**, and that is the
whole point of the script. The standard compressed table is 5836 bytes -- 2918 u16 entries
mixing literal mappings with run-length-encoded identity stretches -- and reproducing it
from memory or from a spec reading is exactly the kind of thing that produces a table that
is subtly wrong in a way nothing catches: the volume still mounts, the directory entry
checksum still matches (it is computed over whatever was written), and filenames simply
compare wrongly for some characters.

Generate a reference on macOS:

    dd if=/dev/zero of=ref.img bs=1m count=64
    hdiutil attach -nomount -imagekey diskimage-class=CRawDiskImage ref.img   # -> /dev/diskN
    newfs_exfat -v REFERENCE /dev/diskN
    hdiutil detach /dev/diskN

then

    scripts/extract-upcase-table.py ref.img > variegated-controller-lib/src/exfat_upcase.rs

The extracted bytes are checked against the checksum stored in the volume's own up-case
directory entry, so a mis-parse fails here rather than producing a plausible constant.
"""

import argparse
import struct
import sys


def table_checksum(data: bytes) -> int:
    """exFAT's table checksum: rotate right one bit, then add, over every byte."""
    checksum = 0
    for byte in data:
        checksum = (((checksum << 31) | (checksum >> 1)) & 0xFFFFFFFF) + byte
        checksum &= 0xFFFFFFFF
    return checksum


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image", help="raw exFAT volume image to extract from")
    args = parser.parse_args()

    with open(args.image, "rb") as handle:
        image = handle.read()

    if image[3:11] != b"EXFAT   ":
        print(
            f"{args.image}: not an exFAT volume (no EXFAT signature at offset 3). "
            "A partitioned image needs the volume extracted first.",
            file=sys.stderr,
        )
        return 1

    cluster_heap_offset, cluster_count = struct.unpack_from("<II", image, 88)
    first_cluster_of_root = struct.unpack_from("<I", image, 96)[0]
    bytes_per_sector_shift = image[108]
    sectors_per_cluster_shift = image[109]

    bytes_per_sector = 1 << bytes_per_sector_shift
    sectors_per_cluster = 1 << sectors_per_cluster_shift

    def cluster_offset(cluster: int) -> int:
        sector = cluster_heap_offset + (cluster - 2) * sectors_per_cluster
        return sector * bytes_per_sector

    # Find the up-case table's own directory entry (type 0x82) in the root directory,
    # rather than assuming it lives at a particular cluster. It carries the location, the
    # length and the checksum, which is what makes this self-verifying.
    root = cluster_offset(first_cluster_of_root)
    entry = None
    for index in range(root, root + sectors_per_cluster * bytes_per_sector, 32):
        if image[index] == 0x82:
            entry = image[index : index + 32]
            break
        if image[index] == 0x00:
            break

    if entry is None:
        print("no up-case table directory entry (0x82) in the root directory", file=sys.stderr)
        return 1

    stored_checksum = struct.unpack_from("<I", entry, 4)[0]
    first_cluster = struct.unpack_from("<I", entry, 20)[0]
    data_length = struct.unpack_from("<Q", entry, 24)[0]

    start = cluster_offset(first_cluster)
    table = image[start : start + data_length]

    computed = table_checksum(table)
    if computed != stored_checksum:
        print(
            f"checksum mismatch: volume says {stored_checksum:#010x}, "
            f"extracted bytes give {computed:#010x}",
            file=sys.stderr,
        )
        return 1

    print("//! The standard exFAT up-case table, extracted from a volume created by")
    print("//! macOS's `newfs_exfat` and verified against the checksum that volume stored")
    print("//! for it. See the script for why this is extracted rather than written out.")
    print("//!")
    print("//! Generated by `scripts/extract-upcase-table.py`. Do not edit by hand.")
    print()
    print("/// The table's checksum, as it must appear in the up-case directory entry.")
    print("///")
    print("/// Stored rather than computed at format time so that a corrupted table cannot")
    print("/// produce a self-consistent volume: the formatter recomputes the checksum over")
    print("/// what it is about to write and asserts it equals this.")
    print(f"pub const UPCASE_TABLE_CHECKSUM: u32 = {stored_checksum:#010x};")
    print()
    print("/// The compressed standard table: literal mappings interleaved with")
    print("/// `0xFFFF`-prefixed runs of identity-mapped characters.")
    print(f"pub const UPCASE_TABLE: [u8; {len(table)}] = [")
    for offset in range(0, len(table), 16):
        row = ", ".join(f"0x{b:02x}" for b in table[offset : offset + 16])
        print(f"    {row},")
    print("];")

    print(
        f"extracted {len(table)} bytes, checksum {stored_checksum:#010x}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
