[package]
name = "variegated-mcp9600"
version = "0.1.0"
edition = "2024"
description = "Basic embedded-hal-async based I2C driver for the MCP9600 and MCP9601 thermocouple amplifier ICs"
repository = "https://github.com/besselfunct/mcp9600"
license = "MIT"
keywords = ["thermocouple","I2C","embedded"]
categories = ["embedded"]

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true
embassy-futures.workspace = true

defmt = { workspace = true, optional = true }

bitvec.workspace = true

[features]
default = []
defmt = ["dep:defmt"]