//! End-to-end tests that validate complete schema generation and structure.

use variegated_postcard_ts_typegen::{PostcardTsTypegen, SchemaGenerator};
use std::collections::BTreeMap;

#[derive(PostcardTsTypegen)]
struct Point {
    x: f32,
    y: f32,
}

#[derive(PostcardTsTypegen)]
enum Status {
    Active,
    Inactive,
    Pending { reason: String },
}

#[derive(PostcardTsTypegen)]
struct Container {
    id: u32,
    name: String,
    point: Point,
    status: Status,
    tags: Vec<String>,
    metadata: BTreeMap<String, String>,
}

/// Validates that a generated schema line matches expected format
#[allow(dead_code)]
fn validate_schema_line(line: &str, expected_patterns: &[&str]) -> bool {
    expected_patterns.iter().all(|pattern| line.contains(pattern))
}

/// Extracts schema definitions from generated TypeScript
fn extract_schema_definitions(output: &str) -> Vec<String> {
    output
        .lines()
        .filter(|line| line.starts_with("export const ") && line.contains("Schema ="))
        .map(|s| s.to_string())
        .collect()
}

/// Extracts type exports from generated TypeScript
fn extract_type_exports(output: &str) -> Vec<String> {
    output
        .lines()
        .filter(|line| line.starts_with("export type ") && line.contains("InferType"))
        .map(|s| s.to_string())
        .collect()
}

#[test]
fn test_complete_schema_structure() {
    let mut generator = SchemaGenerator::new();

    generator.add::<Point>();
    generator.add::<Status>();
    generator.add::<Container>();

    let output = generator.generate();

    // Expected output for Point, Status, and Container types
    let expected = r#"// AUTO-GENERATED by variegated-postcard-ts-typegen
// DO NOT EDIT MANUALLY
//
// IMPORTANT: Field order in struct schemas matches the Rust struct declaration order exactly.
// Postcard serialization is order-dependent - fields are serialized/deserialized in declaration order.

import {
    string,
    f32,
    map,
    u64,
    seq,
    unitVariant,
    option,
    u32,
    struct,
    newtypeVariant,
    f64,
    enumType,
    bool,
    tupleVariant,
    u8,
    u16,
    InferType,
    i8,
    i16,
    i32,
    i64
} from '@variegated-coffee/serde-postcard-ts';

export const PointSchema = struct({
    x: f32(),
    y: f32()
});

export const StatusSchema = enumType('Status', {
    Active: unitVariant('Active'),
    Inactive: unitVariant('Inactive'),
    Pending: newtypeVariant('Pending', struct({
        reason: string()
    }))
});

export const ContainerSchema = struct({
    id: u32(),
    name: string(),
    point: PointSchema,
    status: StatusSchema,
    tags: seq(string()),
    metadata: map(string(), string())
});

// Type exports
export type Point = InferType<typeof PointSchema>;
export type Status = InferType<typeof StatusSchema>;
export type Container = InferType<typeof ContainerSchema>;
"#;

    // Compare the full output to the expected schema
    // This is CRITICAL to ensure the output is correct TypeScript code,
    // both from a syntax standpoint and from a semantics standpoint.
    pretty_assertions::assert_eq!(output, expected,
        "Generated schema does not match expected output for end-to-end test");
}

#[test]
fn test_automatic_dependency_resolution() {
    // Test that adding a root type automatically adds all its dependencies
    use std::collections::BTreeMap;

    #[derive(PostcardTsTypegen)]
    struct Inner {
        value: u32,
    }

    #[derive(PostcardTsTypegen)]
    struct Outer {
        inner: Inner,
        map_field: BTreeMap<String, Inner>,
    }

    let mut generator = SchemaGenerator::new();

    // Only add the outer type - Inner should be added automatically
    generator.add::<Outer>();

    let output = generator.generate();

    // Both Inner and Outer schemas should be present
    assert!(output.contains("export const InnerSchema"));
    assert!(output.contains("export const OuterSchema"));

    // Verify Inner is defined before Outer (dependency ordering)
    let inner_pos = output.find("export const InnerSchema").unwrap();
    let outer_pos = output.find("export const OuterSchema").unwrap();
    assert!(inner_pos < outer_pos, "Inner should be defined before Outer");

    // Verify both type exports are present
    assert!(output.contains("export type Inner ="));
    assert!(output.contains("export type Outer ="));
}

#[test]
fn test_field_order_preservation() {
    #[derive(PostcardTsTypegen)]
    struct OrderedFields {
        first: u8,
        second: u16,
        third: u32,
        fourth: u64,
    }

    let mut generator = SchemaGenerator::new();
    generator.add::<OrderedFields>();
    let output = generator.generate();

    // Extract the struct definition
    let struct_def_start = output.find("export const OrderedFieldsSchema").unwrap();
    let struct_def = &output[struct_def_start..];

    // Verify field order by finding positions
    let first_pos = struct_def.find("first:").unwrap();
    let second_pos = struct_def.find("second:").unwrap();
    let third_pos = struct_def.find("third:").unwrap();
    let fourth_pos = struct_def.find("fourth:").unwrap();

    assert!(first_pos < second_pos);
    assert!(second_pos < third_pos);
    assert!(third_pos < fourth_pos);
}

#[test]
fn test_enum_variant_types() {
    #[derive(PostcardTsTypegen)]
    enum AllVariantTypes {
        Unit,
        Newtype(String),
        Tuple(u32, f32),
        Struct { a: u8, b: u16 },
    }

    let mut generator = SchemaGenerator::new();
    generator.add::<AllVariantTypes>();
    let output = generator.generate();

    // Validate each variant type is correctly generated
    assert!(output.contains("Unit: unitVariant('Unit')"));
    assert!(output.contains("Newtype: newtypeVariant('Newtype', string())"));
    assert!(output.contains("Tuple: tupleVariant('Tuple', u32(), f32())"));
    assert!(output.contains("Struct: newtypeVariant('Struct', struct({"));
    assert!(output.contains("a: u8()"));
    assert!(output.contains("b: u16()"));
}

#[test]
fn test_nested_option_and_vec() {
    #[derive(PostcardTsTypegen)]
    struct Nested {
        optional_vec: Option<Vec<u32>>,
        vec_optional: Vec<Option<String>>,
        deeply_nested: Option<Vec<Option<Vec<u8>>>>,
    }

    let mut generator = SchemaGenerator::new();
    generator.add::<Nested>();
    let output = generator.generate();

    assert!(output.contains("optional_vec: option(seq(u32()))"));
    assert!(output.contains("vec_optional: seq(option(string()))"));
    // This tests proper nesting handling
    assert!(output.contains("deeply_nested: option(seq(option(seq(u8()))))"));
}

#[test]
fn test_map_types() {
    use std::collections::HashMap;

    #[derive(PostcardTsTypegen)]
    struct Maps {
        btree: BTreeMap<String, u32>,
        hash: HashMap<u8, String>,
    }

    let mut generator = SchemaGenerator::new();
    generator.add::<Maps>();
    let output = generator.generate();

    assert!(output.contains("btree: map(string(), u32())"));
    assert!(output.contains("hash: map(u8(), string())"));
}

#[test]
fn test_typescript_syntax_validity() {
    let mut generator = SchemaGenerator::new();
    generator.add::<Point>();
    generator.add::<Status>();
    generator.add::<Container>();

    let output = generator.generate();

    // Check for balanced braces
    let open_braces = output.matches('{').count();
    let close_braces = output.matches('}').count();
    assert_eq!(open_braces, close_braces, "Braces should be balanced");

    // Check for balanced parentheses
    let open_parens = output.matches('(').count();
    let close_parens = output.matches(')').count();
    assert_eq!(open_parens, close_parens, "Parentheses should be balanced");

    // Check that all lines end properly (no missing semicolons on schema definitions)
    for line in output.lines() {
        if line.starts_with("export const ") && line.contains("Schema =") {
            // This line should end in the schema definition section
            let has_closing = output[output.find(line).unwrap()..]
                .lines()
                .take(50)  // Look ahead reasonably
                .any(|l| l.trim().ends_with("});"));
            assert!(has_closing, "Schema definition should have closing braces");
        }
    }
}

#[test]
fn test_no_duplicate_definitions() {
    let mut generator = SchemaGenerator::new();

    // Add the same type multiple times
    generator.add::<Point>();
    generator.add::<Point>();
    generator.add::<Point>();

    let output = generator.generate();

    // Count occurrences of the schema definition
    let count = output.matches("export const PointSchema =").count();
    assert_eq!(count, 1, "Should only have one definition per type");
}
