[package]
name = "variegated-embassy-nau7802"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[features]
default = []

[dependencies]
embedded-hal-async = "1.0"

[dependencies.byteorder]
version = "1.3.4"
default-features = false